// Amazon FPGA Hardware Development Kit
//
// Copyright 2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Amazon Software License (the "License"). You may not use
// this file except in compliance with the License. A copy of the License is
// located at
//
//    http://aws.amazon.com/asl/
//
// or in the "license" file accompanying this file. This file is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, express or
// implied. See the License for the specific language governing permissions and
// limitations under the License.

`pragma protect begin_protected
`pragma protect version = 2
`pragma protect encrypt_agent = "XILINX"
`pragma protect encrypt_agent_info = "Xilinx Encryption Tool 2015"
`pragma protect begin_commonblock
`pragma protect control error_handling="delegated"
`pragma protect end_commonblock
`pragma protect begin_toolblock
`pragma protect rights_digest_method="sha256"
`pragma protect key_keyowner = "Xilinx", key_keyname= "xilinxt_2017_05", key_method = "rsa", key_block
XHka6xAAjiAc3ILyuo9WNroPhLpNJfF7/XGWN3/xH7LhJq7CwReLsMnseGnDJNUzhrJlzzHut0F4
Kf0EvDGOuIPPldFGYswVbL1k8kNZolpc/ghuo0O0BiDCuJdHHrCIqHSkGuOVFmYJILa1oEDJczp0
r6uS7QVMICeG2JO9cuvSK4AhuniopYMQZ8/st+/f57Ow4kW6YKm7vwVRPR3hRWKJ1Q5NQreHst/r
pfvnU/A/xGNYa4erEuTBUa728vN0ugbt0R0EQK5V/6mrpbKvas2Vj9GxqYStZ2De2EacL0aimlMs
jFug3ON9/6lmL1pp0oVhTkFSCANNlyV3ImzUGA==

`pragma protect control xilinx_configuration_visible = "false"
`pragma protect control xilinx_enable_modification = "false"
`pragma protect control xilinx_enable_probing = "false"
`pragma protect end_toolblock="NjLyLyfTBYAz0hzi/Imk3Ytq2xii5cHIWmiemiYog7o="
`pragma protect data_method = "AES128-CBC"
`pragma protect encoding = (enctype = "BASE64", line_length = 76, bytes = 2048)
`pragma protect data_block
UbO3mw3OBY7TAD8TC7SnyrTIaiGp7x2X3glLU3sApSdBai7zLoGod6xNwfr18OFaXHdtYkwocUsd
hah9KK+xTTSBQ6eX08XtwrB5cbBs6XzgC+iXn3dEhmfjUuUnVegM+jX4zXmTaJz++Axouf9ysh5r
8K63H8xIWZG+JBnbIjOxz8dHKzYbhNA5W4i+IJr5K3JvF5wOR1Zp3730EH8lPboRw/tAorYmb4rj
cuW8hx+WF5w3XtDrHAtfNNXmaiJxU9rqUzfntaOy9ALRSx4bLFZLW1BFRSRzR84RwkTerV4suNYp
uqEeWiHs3py1No2kxHhVdrVivK8ePM+ybBLeBxpf1WKczs/NfNFxjI7ChLNZ+SjqTl/3CveUCQEK
8t0W+idcYWe6Ky50YFrzEv/3dMibjXhjucFmT8oJSGuo2e360lwQzOtW33hx4rvBDKfQl26vJGK3
N42slfrqqrwqKV4MDtEgf32+cY9yQlRwwIr0xUj7g5O//GM/B0c+G40Bl8oGgmw/raIh41Csz1ef
SyjRLBbV9m5Wo8w3dulZliAJCzdJibcqYGE9qRTHtlfHgYOOUUc41/7ZA6Fk3t5I+QlZALLOhrvN
ckVopwHdj78HvBuCL9Jb4Nh2TEgw0X93Ngp+XpD/KQbVVFCxPG6tAmO90UCAl+v/mAfVYRN39SKu
sN99Ur4FsMz39eypjwHjSltqdmFxSZvl8/LnYQ3seJrg8ceTP5A5uhqWMBT3CWPnEX6pjj/7/FUz
qKOX4QwLKwOZb33wcKGW0C0+e/eB8UgoAcwpcpjA8VdndrH7DzYWZS5bM3GUALzFKuGJDB8W77m0
a7EevxwOZimTCgUBfQo1VeStUydb/ksk2po+hHGSMpl3nOelthv5GP3OTlfOS7eJEGYSYM1AvryC
r+vZvTuYUgzi8HpelSQ5tCbWM9CQHJiRc4jJon8gHJFrewkFjMG5p90C6fzwZxCV9eitrG4wGKPF
Dlj1xNmNxFTwMtVjgrzFcrfkVvMH2PdsktBlD93rfyWVOBg63QXhDpurcVQIKbkt3I5KR+gkJlKl
ZnzkKJsp6urWsjq/hD8nou6QsKpdO9Y73iVGwv6UNnOd+k6eXIOucVnpHIeuJURymUEGpdja3I0R
cJ00ntE4zikx343SVVH7mJHVBc/RhWxFayFvMtfaE/4cZOoFShg8KiFhXg2/l+0MuZ8gPjf8f6cS
gJteugkIo9sU25ifXqbLupLCpgNthDeB7tRoYQckd2lrh2/KD3HlrrJQqItmq3eCaGdTOgys3vzO
961OItE1yjupaTckEPSX2w0Xkl4EK8D6e8lBXv+23nsI29uTEwhcWsmRxtk9959zqGVNZjUxj8om
TQNU4SAcHY8dG9UodhKTDhoRA3wxzGgAPfRfJoxpXAa0Jigp+PCbr6X5yzVp2h3nivA409JfBroE
dIJyGCQjLni6COFBYULh9eLJ/6c65cjU4aafNiKAru6TOrPgOXwcq2qE4v/9pmokKFEtsZcdMTkn
BXz0VzZfzYdpv1S1izL3NRVSzzspUV+/X2JEWnFKZTxOM5QgNiANRJxPGmMOzxPTBadS6JBmx8ic
bIUOd0HmfBhJH/hYwRQ2irq1zqhSbQhcHrmMhPA45p7lGBoA5Tgt3AgGfdzb4BVhAL2sYs6dAGgY
72bd3oGB0ELaWn18TUhKBYy4uFHE5FUnkYlrp0lge4T3++KxN+nlUFIxGlJz6z4/NMKzTBjfAr8c
+a51UxD00sX3Gc52aXcTEWNowBH4JPCDjEe0uwQ+AlgraXaiZwPa+QiCtyjaHP7/rAYj+NvOeUcE
lZWScwF4KQobje+SHoLwpFrYYSCw1ZVITBW5qjckokWGyki4lL9Fe+zw1OoTQ6YeG5S4vMa1FhUv
MyhL5FAiz4vPbf9kigOGAABq+WgJvKn0Vsc63mIiFkNhvYnmCu7haZ+3kEDmYIT3x4JSQ0gyxrBR
tlR2RqX+ZpvkRXSwD3U7VTu0fF/y9FuRPtFXf9YbNCza+BnWi8vfnXWwkbtwjMOTHqWrXlmNxPx3
IgpcL8HTz0yRE1ulaNFnudPC9seopOouNTorCMpmhMtTKKWjhPC6YoxHrLhPtFMcPZREcUoB3TZN
Fnl6lZ2Waftp6cQGSnXvrjq9yG80gRZHjkLJcstsxSwYVHmrGNiLnGtXJXt9rD84FqhKPMAapvkq
ZvalYlmp3IobNJoEkWin9UKy58Yl5YA2laM3rHtCpjJ09t2c+THzzEy4ES1VXngkUAvynkpcXI2D
Xl9YQQ+PipXnIROJg+3Mp6JnL1hqVawE6iNMX7b4+CRj+SdMONDgkmuhMZFEbVnpPgB2k1+FrvsG
1aSctImrBS5IVEloHBA6Iyj+8tx4Pk8voBmg9scSXuvllW0k7umVgolHWxl2W4aW65MuIoXXTqeS
M0uqt7Jz58g+Y8WVSYtHbOwMpCoLAtMlabOipeb+xzS7twiLX9YDOd3JDk4EP+AFeDR0zF2U3CT8
pqz7uEw992RcBFjwGcmxJgLZw1NVLKf9xJ57XGZZ+crEBH8tmP1QuMGUSS4MkyDwPfAAEQuc9ZZ5
HvQwUI9tIdMs9IcSy1Dx4yOrBoZjK7WQqWxsNoSzOg+gG1AQr++BdTCenMzNT1BGNHs+HpgT/pHG
i1+xtwh9vyj69EDLc9rAWFC/p8QCXW4ofUy+CtKKJhfBIIo1kLcg4HriDI2K1bC27yPN/S4=
`pragma protect end_protected
