// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xdds.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XDds_CfgInitialize(XDds *InstancePtr, XDds_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Prog_bus_BaseAddress = ConfigPtr->Prog_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XDds_Start(XDds *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDds_ReadReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_AP_CTRL) & 0x80;
    XDds_WriteReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XDds_IsDone(XDds *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDds_ReadReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XDds_IsIdle(XDds *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDds_ReadReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XDds_IsReady(XDds *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDds_ReadReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XDds_EnableAutoRestart(XDds *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDds_WriteReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_AP_CTRL, 0x80);
}

void XDds_DisableAutoRestart(XDds *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDds_WriteReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_AP_CTRL, 0);
}

void XDds_Set_nofSample(XDds *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDds_WriteReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_NOFSAMPLE_DATA, Data);
}

u32 XDds_Get_nofSample(XDds *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDds_ReadReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_NOFSAMPLE_DATA);
    return Data;
}

void XDds_Set_incr_V(XDds *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDds_WriteReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_INCR_V_DATA, Data);
}

u32 XDds_Get_incr_V(XDds *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XDds_ReadReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_INCR_V_DATA);
    return Data;
}

void XDds_InterruptGlobalEnable(XDds *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDds_WriteReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_GIE, 1);
}

void XDds_InterruptGlobalDisable(XDds *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDds_WriteReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_GIE, 0);
}

void XDds_InterruptEnable(XDds *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDds_ReadReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_IER);
    XDds_WriteReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_IER, Register | Mask);
}

void XDds_InterruptDisable(XDds *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XDds_ReadReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_IER);
    XDds_WriteReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_IER, Register & (~Mask));
}

void XDds_InterruptClear(XDds *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XDds_WriteReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_ISR, Mask);
}

u32 XDds_InterruptGetEnabled(XDds *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDds_ReadReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_IER);
}

u32 XDds_InterruptGetStatus(XDds *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XDds_ReadReg(InstancePtr->Prog_bus_BaseAddress, XDDS_PROG_BUS_ADDR_ISR);
}

