// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.3
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdds.h"

extern XDds_Config XDds_ConfigTable[];

XDds_Config *XDds_LookupConfig(u16 DeviceId) {
	XDds_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDDS_NUM_INSTANCES; Index++) {
		if (XDds_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDds_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDds_Initialize(XDds *InstancePtr, u16 DeviceId) {
	XDds_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDds_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDds_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

