-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.3
-- Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity process_r is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_ce : IN STD_LOGIC;
    incr_V : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of process_r is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv18_0 : STD_LOGIC_VECTOR (17 downto 0) := "000000000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv18_1FFFF : STD_LOGIC_VECTOR (17 downto 0) := "011111111111111111";
    constant ap_const_lv18_20001 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000001";
    constant ap_const_lv25_0 : STD_LOGIC_VECTOR (24 downto 0) := "0000000000000000000000000";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_2A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101010";
    constant ap_const_lv26_0 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000000000000";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8001 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000001";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal dds_0_acc_V : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal dds_0_cos_lut_V_address0 : STD_LOGIC_VECTOR (9 downto 0);
    signal dds_0_cos_lut_V_ce0 : STD_LOGIC;
    signal dds_0_cos_lut_V_q0 : STD_LOGIC_VECTOR (16 downto 0);
    signal dds_0_cos_lut_V_address1 : STD_LOGIC_VECTOR (9 downto 0);
    signal dds_0_cos_lut_V_ce1 : STD_LOGIC;
    signal dds_0_cos_lut_V_q1 : STD_LOGIC_VECTOR (16 downto 0);
    signal dds_0_fine_lut_V_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal dds_0_fine_lut_V_ce0 : STD_LOGIC;
    signal dds_0_fine_lut_V_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal msb_V_reg_952 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_pipeline_reg_pp0_iter1_msb_V_reg_952 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_pipeline_reg_pp0_iter2_msb_V_reg_952 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_pipeline_reg_pp0_iter3_msb_V_reg_952 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_pipeline_reg_pp0_iter4_msb_V_reg_952 : STD_LOGIC_VECTOR (1 downto 0);
    signal lsb_V_reg_959 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_pipeline_reg_pp0_iter1_lsb_V_reg_959 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_Result_8_reg_966 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_pipeline_reg_pp0_iter1_p_Result_8_reg_966 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_pipeline_reg_pp0_iter2_p_Result_8_reg_966 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_pipeline_reg_pp0_iter3_p_Result_8_reg_966 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_pipeline_reg_pp0_iter4_p_Result_8_reg_966 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_pipeline_reg_pp0_iter5_p_Result_8_reg_966 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_pipeline_reg_pp0_iter6_p_Result_8_reg_966 : STD_LOGIC_VECTOR (8 downto 0);
    signal sin_adr_V_fu_169_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal sin_adr_V_reg_971 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_2_fu_178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_981 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter3_tmp_2_reg_981 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter4_tmp_2_reg_981 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter5_tmp_2_reg_981 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_6_reg_996 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_4_reg_1001 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_pipeline_reg_pp0_iter4_p_Val2_4_reg_1001 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_pipeline_reg_pp0_iter5_p_Val2_4_reg_1001 : STD_LOGIC_VECTOR (16 downto 0);
    signal dds_0_cos_lut_V_load_fu_187_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal dds_0_cos_lut_V_load_reg_1007 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_pipeline_reg_pp0_iter5_dds_0_cos_lut_V_load_reg_1007 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_pipeline_reg_pp0_iter6_dds_0_cos_lut_V_load_reg_1007 : STD_LOGIC_VECTOR (17 downto 0);
    signal dds_0_cos_lut_V_load_2_fu_190_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal dds_0_cos_lut_V_load_2_reg_1014 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_pipeline_reg_pp0_iter5_dds_0_cos_lut_V_load_2_reg_1014 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_5_fu_193_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_5_reg_1019 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_pipeline_reg_pp0_iter5_p_Val2_5_reg_1019 : STD_LOGIC_VECTOR (17 downto 0);
    signal isneg_reg_1025 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_7_fu_207_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_7_reg_1030 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_pipeline_reg_pp0_iter5_p_Val2_7_reg_1030 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_pipeline_reg_pp0_iter6_p_Val2_7_reg_1030 : STD_LOGIC_VECTOR (17 downto 0);
    signal isneg_1_reg_1036 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_221_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_27_reg_1041 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_28_fu_225_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_28_reg_1046 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_s_fu_229_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1051 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_1058 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_fu_239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_1063 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_reg_1069 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_1_fu_259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_1_reg_1076 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter6_underflow_1_reg_1076 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_reg_1084 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_demorgan_fu_269_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_demorgan_reg_1090 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_74_mux_fu_280_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_74_mux_reg_1096 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_0_i_i_fu_286_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_0_i_i_reg_1101 : STD_LOGIC_VECTOR (16 downto 0);
    signal p_Val2_1_fu_303_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_1_reg_1106 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_pipeline_reg_pp0_iter7_p_Val2_1_reg_1106 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_0_i_i1_fu_321_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_0_i_i1_reg_1114 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp9_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_reg_1119 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_fu_338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp5_reg_1124 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_reg_1129 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp12_reg_1134 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_362_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_reg_1140 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter7_sel_tmp14_reg_1140 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_reg_1146 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter7_sel_tmp17_reg_1146 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp20_fu_394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp20_reg_1152 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter7_sel_tmp20_reg_1152 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp23_fu_414_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp23_reg_1158 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_0_i_i_cast_fu_422_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_0_i_i_cast_reg_1163 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp13_fu_448_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp13_reg_1168 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_1_8_fu_474_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_1_8_reg_1173 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_pipeline_reg_pp0_iter8_p_Val2_1_8_reg_1173 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_pipeline_reg_pp0_iter9_p_Val2_1_8_reg_1173 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_pipeline_reg_pp0_iter10_p_Val2_1_8_reg_1173 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_8_fu_495_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_8_reg_1184 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_pipeline_reg_pp0_iter9_p_Val2_8_reg_1184 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_pipeline_reg_pp0_iter10_p_Val2_8_reg_1184 : STD_LOGIC_VECTOR (17 downto 0);
    signal fine_word_V_reg_1190 : STD_LOGIC_VECTOR (15 downto 0);
    signal OP2_V_cast_fu_504_p1 : STD_LOGIC_VECTOR (33 downto 0);
    signal grp_fu_930_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal p_Val2_9_reg_1221 : STD_LOGIC_VECTOR (43 downto 0);
    signal ap_pipeline_reg_pp0_iter13_p_Val2_9_reg_1221 : STD_LOGIC_VECTOR (43 downto 0);
    signal signbit_reg_1228 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter13_signbit_reg_1228 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter14_signbit_reg_1228 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter15_signbit_reg_1228 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_fu_539_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_31_reg_1236 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_32_reg_1241 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter13_tmp_32_reg_1241 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter14_tmp_32_reg_1241 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter15_tmp_32_reg_1241 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_941_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal p_Val2_13_reg_1247 : STD_LOGIC_VECTOR (43 downto 0);
    signal ap_pipeline_reg_pp0_iter13_p_Val2_13_reg_1247 : STD_LOGIC_VECTOR (43 downto 0);
    signal signbit_1_reg_1254 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter13_signbit_1_reg_1254 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter14_signbit_1_reg_1254 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter15_signbit_1_reg_1254 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_fu_556_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_38_reg_1262 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_39_reg_1267 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter13_tmp_39_reg_1267 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter14_tmp_39_reg_1267 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter15_tmp_39_reg_1267 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_fu_566_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_reg_1273 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_fu_571_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_reg_1278 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_11_fu_614_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_11_reg_1283 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_pipeline_reg_pp0_iter15_p_Val2_11_reg_1283 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_pipeline_reg_pp0_iter16_p_Val2_11_reg_1283 : STD_LOGIC_VECTOR (15 downto 0);
    signal newsignbit_reg_1289 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter15_newsignbit_reg_1289 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_fu_628_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_35_reg_1297 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_Val2_15_fu_670_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_15_reg_1302 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_pipeline_reg_pp0_iter15_p_Val2_15_reg_1302 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_pipeline_reg_pp0_iter16_p_Val2_15_reg_1302 : STD_LOGIC_VECTOR (15 downto 0);
    signal newsignbit_1_reg_1308 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter15_newsignbit_1_reg_1308 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_fu_684_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_42_reg_1316 : STD_LOGIC_VECTOR (14 downto 0);
    signal overflow_fu_720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_reg_1321 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter16_overflow_reg_1321 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_742_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_1327 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_1_fu_780_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_1_reg_1332 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter16_overflow_1_reg_1332 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_802_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_reg_1338 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_2_fu_823_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_2_reg_1343 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_3_fu_843_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_3_reg_1350 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_174_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_183_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_480_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_Val2_3_fu_127_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_7_fu_297_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal underflow_12_not_fu_275_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_309_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp4_fu_333_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp11_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_14_not_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp33_demorgan_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp16_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp42_demorgan_fu_383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp19_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp21_fu_400_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp22_fu_407_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp3_fu_431_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp6_fu_436_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp8_fu_442_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal p_Val2_77_mux_fu_425_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp24_fu_455_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp25_fu_460_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp26_fu_467_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp15_fu_484_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal sel_tmp18_fu_489_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_9_fu_510_p3 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_17_fu_521_p3 : STD_LOGIC_VECTOR (42 downto 0);
    signal tmp_33_fu_592_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_i_i_fu_599_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal qbit_fu_585_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal qb_assign_1_fu_604_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_610_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_10_fu_576_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_40_fu_648_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_i_i1_fu_655_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal qbit_1_fu_641_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal qb_assign_3_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_666_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_14_fu_632_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_12_fu_688_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_fu_693_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i_fu_710_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i4_fu_715_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_fu_703_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_fu_737_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_i_fu_731_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_fu_748_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal carry_1_fu_753_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_758_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i1_fu_770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i5_fu_775_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_ones_1_fu_763_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_demorgan_i_1_fu_786_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_797_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge40_i1_fu_791_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_2_not_fu_808_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_813_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_818_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_11_not_fu_828_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_833_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp9_fu_838_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal underflow_16_not_fu_852_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i4_fu_848_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge6_fu_857_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_87_mux_fu_862_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_4_9_fu_869_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal underflow_17_not_fu_887_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_i5_fu_883_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge7_fu_892_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_91_mux_fu_897_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_Val2_5_10_fu_904_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal cos_dds_V_fu_875_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal sin_dds_V_fu_910_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_930_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_941_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_930_ce : STD_LOGIC;
    signal grp_fu_941_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_idle_pp0 : STD_LOGIC;

    component dds_mac_mulsub_18dEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (42 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (43 downto 0) );
    end component;


    component dds_mac_muladd_16eOg IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        din2 : IN STD_LOGIC_VECTOR (42 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (43 downto 0) );
    end component;


    component process_r_dds_0_cbkb IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (16 downto 0);
        address1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component process_r_dds_0_fcud IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    dds_0_cos_lut_V_U : component process_r_dds_0_cbkb
    generic map (
        DataWidth => 17,
        AddressRange => 1024,
        AddressWidth => 10)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dds_0_cos_lut_V_address0,
        ce0 => dds_0_cos_lut_V_ce0,
        q0 => dds_0_cos_lut_V_q0,
        address1 => dds_0_cos_lut_V_address1,
        ce1 => dds_0_cos_lut_V_ce1,
        q1 => dds_0_cos_lut_V_q1);

    dds_0_fine_lut_V_U : component process_r_dds_0_fcud
    generic map (
        DataWidth => 16,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dds_0_fine_lut_V_address0,
        ce0 => dds_0_fine_lut_V_ce0,
        q0 => dds_0_fine_lut_V_q0);

    dds_mac_mulsub_18dEe_U0 : component dds_mac_mulsub_18dEe
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 18,
        din1_WIDTH => 16,
        din2_WIDTH => 43,
        dout_WIDTH => 44)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ap_pipeline_reg_pp0_iter8_p_Val2_1_8_reg_1173,
        din1 => grp_fu_930_p1,
        din2 => tmp_9_fu_510_p3,
        ce => grp_fu_930_ce,
        dout => grp_fu_930_p3);

    dds_mac_muladd_16eOg_U1 : component dds_mac_muladd_16eOg
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 18,
        din2_WIDTH => 43,
        dout_WIDTH => 44)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_941_p0,
        din1 => p_Val2_8_reg_1184,
        din2 => tmp_17_fu_521_p3,
        ce => grp_fu_941_ce,
        dout => grp_fu_941_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce)))))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if (not((((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)) or not((ap_const_logic_1 = ap_ce))))) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce))) then
                ap_pipeline_reg_pp0_iter10_p_Val2_1_8_reg_1173 <= ap_pipeline_reg_pp0_iter9_p_Val2_1_8_reg_1173;
                ap_pipeline_reg_pp0_iter10_p_Val2_8_reg_1184 <= ap_pipeline_reg_pp0_iter9_p_Val2_8_reg_1184;
                ap_pipeline_reg_pp0_iter13_p_Val2_13_reg_1247 <= p_Val2_13_reg_1247;
                ap_pipeline_reg_pp0_iter13_p_Val2_9_reg_1221 <= p_Val2_9_reg_1221;
                ap_pipeline_reg_pp0_iter13_signbit_1_reg_1254 <= signbit_1_reg_1254;
                ap_pipeline_reg_pp0_iter13_signbit_reg_1228 <= signbit_reg_1228;
                ap_pipeline_reg_pp0_iter13_tmp_32_reg_1241 <= tmp_32_reg_1241;
                ap_pipeline_reg_pp0_iter13_tmp_39_reg_1267 <= tmp_39_reg_1267;
                ap_pipeline_reg_pp0_iter14_signbit_1_reg_1254 <= ap_pipeline_reg_pp0_iter13_signbit_1_reg_1254;
                ap_pipeline_reg_pp0_iter14_signbit_reg_1228 <= ap_pipeline_reg_pp0_iter13_signbit_reg_1228;
                ap_pipeline_reg_pp0_iter14_tmp_32_reg_1241 <= ap_pipeline_reg_pp0_iter13_tmp_32_reg_1241;
                ap_pipeline_reg_pp0_iter14_tmp_39_reg_1267 <= ap_pipeline_reg_pp0_iter13_tmp_39_reg_1267;
                ap_pipeline_reg_pp0_iter15_newsignbit_1_reg_1308 <= newsignbit_1_reg_1308;
                ap_pipeline_reg_pp0_iter15_newsignbit_reg_1289 <= newsignbit_reg_1289;
                ap_pipeline_reg_pp0_iter15_p_Val2_11_reg_1283 <= p_Val2_11_reg_1283;
                ap_pipeline_reg_pp0_iter15_p_Val2_15_reg_1302 <= p_Val2_15_reg_1302;
                ap_pipeline_reg_pp0_iter15_signbit_1_reg_1254 <= ap_pipeline_reg_pp0_iter14_signbit_1_reg_1254;
                ap_pipeline_reg_pp0_iter15_signbit_reg_1228 <= ap_pipeline_reg_pp0_iter14_signbit_reg_1228;
                ap_pipeline_reg_pp0_iter15_tmp_32_reg_1241 <= ap_pipeline_reg_pp0_iter14_tmp_32_reg_1241;
                ap_pipeline_reg_pp0_iter15_tmp_39_reg_1267 <= ap_pipeline_reg_pp0_iter14_tmp_39_reg_1267;
                ap_pipeline_reg_pp0_iter16_overflow_1_reg_1332 <= overflow_1_reg_1332;
                ap_pipeline_reg_pp0_iter16_overflow_reg_1321 <= overflow_reg_1321;
                ap_pipeline_reg_pp0_iter16_p_Val2_11_reg_1283 <= ap_pipeline_reg_pp0_iter15_p_Val2_11_reg_1283;
                ap_pipeline_reg_pp0_iter16_p_Val2_15_reg_1302 <= ap_pipeline_reg_pp0_iter15_p_Val2_15_reg_1302;
                ap_pipeline_reg_pp0_iter2_msb_V_reg_952 <= ap_pipeline_reg_pp0_iter1_msb_V_reg_952;
                ap_pipeline_reg_pp0_iter2_p_Result_8_reg_966 <= ap_pipeline_reg_pp0_iter1_p_Result_8_reg_966;
                ap_pipeline_reg_pp0_iter3_msb_V_reg_952 <= ap_pipeline_reg_pp0_iter2_msb_V_reg_952;
                ap_pipeline_reg_pp0_iter3_p_Result_8_reg_966 <= ap_pipeline_reg_pp0_iter2_p_Result_8_reg_966;
                ap_pipeline_reg_pp0_iter3_tmp_2_reg_981 <= tmp_2_reg_981;
                ap_pipeline_reg_pp0_iter4_msb_V_reg_952 <= ap_pipeline_reg_pp0_iter3_msb_V_reg_952;
                ap_pipeline_reg_pp0_iter4_p_Result_8_reg_966 <= ap_pipeline_reg_pp0_iter3_p_Result_8_reg_966;
                ap_pipeline_reg_pp0_iter4_p_Val2_4_reg_1001 <= p_Val2_4_reg_1001;
                ap_pipeline_reg_pp0_iter4_tmp_2_reg_981 <= ap_pipeline_reg_pp0_iter3_tmp_2_reg_981;
                    ap_pipeline_reg_pp0_iter5_dds_0_cos_lut_V_load_2_reg_1014(16 downto 0) <= dds_0_cos_lut_V_load_2_reg_1014(16 downto 0);
                    ap_pipeline_reg_pp0_iter5_dds_0_cos_lut_V_load_reg_1007(16 downto 0) <= dds_0_cos_lut_V_load_reg_1007(16 downto 0);
                ap_pipeline_reg_pp0_iter5_p_Result_8_reg_966 <= ap_pipeline_reg_pp0_iter4_p_Result_8_reg_966;
                ap_pipeline_reg_pp0_iter5_p_Val2_4_reg_1001 <= ap_pipeline_reg_pp0_iter4_p_Val2_4_reg_1001;
                ap_pipeline_reg_pp0_iter5_p_Val2_5_reg_1019 <= p_Val2_5_reg_1019;
                ap_pipeline_reg_pp0_iter5_p_Val2_7_reg_1030 <= p_Val2_7_reg_1030;
                ap_pipeline_reg_pp0_iter5_tmp_2_reg_981 <= ap_pipeline_reg_pp0_iter4_tmp_2_reg_981;
                    ap_pipeline_reg_pp0_iter6_dds_0_cos_lut_V_load_reg_1007(16 downto 0) <= ap_pipeline_reg_pp0_iter5_dds_0_cos_lut_V_load_reg_1007(16 downto 0);
                ap_pipeline_reg_pp0_iter6_p_Result_8_reg_966 <= ap_pipeline_reg_pp0_iter5_p_Result_8_reg_966;
                ap_pipeline_reg_pp0_iter6_p_Val2_7_reg_1030 <= ap_pipeline_reg_pp0_iter5_p_Val2_7_reg_1030;
                ap_pipeline_reg_pp0_iter6_underflow_1_reg_1076 <= underflow_1_reg_1076;
                ap_pipeline_reg_pp0_iter7_p_Val2_1_reg_1106 <= p_Val2_1_reg_1106;
                ap_pipeline_reg_pp0_iter7_sel_tmp14_reg_1140 <= sel_tmp14_reg_1140;
                ap_pipeline_reg_pp0_iter7_sel_tmp17_reg_1146 <= sel_tmp17_reg_1146;
                ap_pipeline_reg_pp0_iter7_sel_tmp20_reg_1152 <= sel_tmp20_reg_1152;
                ap_pipeline_reg_pp0_iter8_p_Val2_1_8_reg_1173 <= p_Val2_1_8_reg_1173;
                ap_pipeline_reg_pp0_iter9_p_Val2_1_8_reg_1173 <= ap_pipeline_reg_pp0_iter8_p_Val2_1_8_reg_1173;
                ap_pipeline_reg_pp0_iter9_p_Val2_8_reg_1184 <= p_Val2_8_reg_1184;
                    dds_0_cos_lut_V_load_2_reg_1014(16 downto 0) <= dds_0_cos_lut_V_load_2_fu_190_p1(16 downto 0);
                    dds_0_cos_lut_V_load_reg_1007(16 downto 0) <= dds_0_cos_lut_V_load_fu_187_p1(16 downto 0);
                fine_word_V_reg_1190 <= dds_0_fine_lut_V_q0;
                isneg_1_reg_1036 <= p_Val2_7_fu_207_p2(17 downto 17);
                isneg_reg_1025 <= p_Val2_5_fu_193_p2(17 downto 17);
                newsignbit_1_reg_1308 <= p_Val2_15_fu_670_p2(15 downto 15);
                newsignbit_reg_1289 <= p_Val2_11_fu_614_p2(15 downto 15);
                overflow_1_reg_1332 <= overflow_1_fu_780_p2;
                overflow_reg_1321 <= overflow_fu_720_p2;
                p_Val2_0_i_i1_reg_1114 <= p_Val2_0_i_i1_fu_321_p3;
                p_Val2_0_i_i_reg_1101 <= p_Val2_0_i_i_fu_286_p3;
                p_Val2_11_reg_1283 <= p_Val2_11_fu_614_p2;
                p_Val2_15_reg_1302 <= p_Val2_15_fu_670_p2;
                p_Val2_1_8_reg_1173 <= p_Val2_1_8_fu_474_p3;
                p_Val2_1_reg_1106 <= p_Val2_1_fu_303_p3;
                p_Val2_5_reg_1019 <= p_Val2_5_fu_193_p2;
                p_Val2_74_mux_reg_1096 <= p_Val2_74_mux_fu_280_p3;
                p_Val2_7_reg_1030 <= p_Val2_7_fu_207_p2;
                p_Val2_8_reg_1184 <= p_Val2_8_fu_495_p3;
                r_1_reg_1278 <= r_1_fu_571_p2;
                r_reg_1273 <= r_fu_566_p2;
                sel_tmp12_reg_1134 <= sel_tmp12_fu_357_p2;
                sel_tmp14_reg_1140 <= sel_tmp14_fu_362_p2;
                sel_tmp17_reg_1146 <= sel_tmp17_fu_378_p2;
                sel_tmp18_demorgan_reg_1090 <= sel_tmp18_demorgan_fu_269_p2;
                sel_tmp1_reg_1084 <= sel_tmp1_fu_264_p2;
                sel_tmp20_reg_1152 <= sel_tmp20_fu_394_p2;
                sel_tmp23_reg_1158 <= sel_tmp23_fu_414_p3;
                sel_tmp5_reg_1124 <= sel_tmp5_fu_338_p2;
                sel_tmp7_reg_1129 <= sel_tmp7_fu_343_p2;
                sel_tmp9_reg_1119 <= sel_tmp9_fu_329_p2;
                signbit_1_reg_1254 <= grp_fu_941_p3(43 downto 43);
                signbit_reg_1228 <= grp_fu_930_p3(43 downto 43);
                tmp_16_reg_1327 <= tmp_16_fu_742_p2;
                tmp_24_reg_1338 <= tmp_24_fu_802_p2;
                tmp_27_reg_1041 <= tmp_27_fu_221_p1;
                tmp_28_reg_1046 <= tmp_28_fu_225_p1;
                tmp_2_reg_981 <= tmp_2_fu_178_p2;
                tmp_31_reg_1236 <= tmp_31_fu_539_p1;
                tmp_32_reg_1241 <= grp_fu_930_p3(42 downto 42);
                tmp_35_reg_1297 <= tmp_35_fu_628_p1;
                tmp_38_reg_1262 <= tmp_38_fu_556_p1;
                tmp_39_reg_1267 <= grp_fu_941_p3(42 downto 42);
                tmp_3_reg_1058 <= tmp_3_fu_234_p2;
                tmp_42_reg_1316 <= tmp_42_fu_684_p1;
                tmp_6_reg_1063 <= tmp_6_fu_239_p2;
                tmp_s_reg_1051 <= tmp_s_fu_229_p2;
                underflow_1_reg_1076 <= underflow_1_fu_259_p2;
                underflow_2_reg_1343 <= underflow_2_fu_823_p2;
                underflow_3_reg_1350 <= underflow_3_fu_843_p2;
                underflow_reg_1069 <= underflow_fu_249_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce))) then
                ap_pipeline_reg_pp0_iter1_lsb_V_reg_959 <= lsb_V_reg_959;
                ap_pipeline_reg_pp0_iter1_msb_V_reg_952 <= msb_V_reg_952;
                ap_pipeline_reg_pp0_iter1_p_Result_8_reg_966 <= p_Result_8_reg_966;
                lsb_V_reg_959 <= p_Val2_3_fu_127_p2(29 downto 20);
                msb_V_reg_952 <= p_Val2_3_fu_127_p2(31 downto 30);
                p_Result_8_reg_966 <= p_Val2_3_fu_127_p2(19 downto 11);
                sin_adr_V_reg_971 <= sin_adr_V_fu_169_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce))) then
                dds_0_acc_V <= p_Val2_3_fu_127_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce) and (sel_tmp17_reg_1146 = ap_const_lv1_0) and (sel_tmp20_reg_1152 = ap_const_lv1_0))) then
                    p_Val2_0_i_i_cast_reg_1163(16 downto 0) <= p_Val2_0_i_i_cast_fu_422_p1(16 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_enable_reg_pp0_iter12))) then
                p_Val2_13_reg_1247 <= grp_fu_941_p3;
                p_Val2_9_reg_1221 <= grp_fu_930_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3))) then
                p_Val2_4_reg_1001 <= dds_0_cos_lut_V_q1;
                p_Val2_6_reg_996 <= dds_0_cos_lut_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce) and (sel_tmp17_reg_1146 = ap_const_lv1_0) and (sel_tmp20_reg_1152 = ap_const_lv1_0) and (sel_tmp14_reg_1140 = ap_const_lv1_0))) then
                sel_tmp13_reg_1168 <= sel_tmp13_fu_448_p3;
            end if;
        end if;
    end process;
    dds_0_cos_lut_V_load_reg_1007(17) <= '0';
    ap_pipeline_reg_pp0_iter5_dds_0_cos_lut_V_load_reg_1007(17) <= '0';
    ap_pipeline_reg_pp0_iter6_dds_0_cos_lut_V_load_reg_1007(17) <= '0';
    dds_0_cos_lut_V_load_2_reg_1014(17) <= '0';
    ap_pipeline_reg_pp0_iter5_dds_0_cos_lut_V_load_2_reg_1014(17) <= '0';
    p_Val2_0_i_i_cast_reg_1163(17) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_enable_reg_pp0_iter0, ap_ce, ap_pipeline_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    OP2_V_cast_fu_504_p1 <= std_logic_vector(resize(unsigned(fine_word_V_reg_1190),34));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0 downto 0);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter17, ap_ce)
    begin
        if ((((ap_const_logic_0 = ap_start) and (ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0)) or (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_enable_reg_pp0_iter17)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter3) and (ap_const_logic_0 = ap_enable_reg_pp0_iter4) and (ap_const_logic_0 = ap_enable_reg_pp0_iter5) and (ap_const_logic_0 = ap_enable_reg_pp0_iter6) and (ap_const_logic_0 = ap_enable_reg_pp0_iter7) and (ap_const_logic_0 = ap_enable_reg_pp0_iter8) and (ap_const_logic_0 = ap_enable_reg_pp0_iter9) and (ap_const_logic_0 = ap_enable_reg_pp0_iter10) and (ap_const_logic_0 = ap_enable_reg_pp0_iter11) and (ap_const_logic_0 = ap_enable_reg_pp0_iter12) and (ap_const_logic_0 = ap_enable_reg_pp0_iter13) and (ap_const_logic_0 = ap_enable_reg_pp0_iter14) and (ap_const_logic_0 = ap_enable_reg_pp0_iter15) and (ap_const_logic_0 = ap_enable_reg_pp0_iter16) and (ap_const_logic_0 = ap_enable_reg_pp0_iter17))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_pipeline_idle_pp0_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter3) and (ap_const_logic_0 = ap_enable_reg_pp0_iter4) and (ap_const_logic_0 = ap_enable_reg_pp0_iter5) and (ap_const_logic_0 = ap_enable_reg_pp0_iter6) and (ap_const_logic_0 = ap_enable_reg_pp0_iter7) and (ap_const_logic_0 = ap_enable_reg_pp0_iter8) and (ap_const_logic_0 = ap_enable_reg_pp0_iter9) and (ap_const_logic_0 = ap_enable_reg_pp0_iter10) and (ap_const_logic_0 = ap_enable_reg_pp0_iter11) and (ap_const_logic_0 = ap_enable_reg_pp0_iter12) and (ap_const_logic_0 = ap_enable_reg_pp0_iter13) and (ap_const_logic_0 = ap_enable_reg_pp0_iter14) and (ap_const_logic_0 = ap_enable_reg_pp0_iter15) and (ap_const_logic_0 = ap_enable_reg_pp0_iter16))) then 
            ap_pipeline_idle_pp0 <= ap_const_logic_1;
        else 
            ap_pipeline_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return_0 <= cos_dds_V_fu_875_p3;
    ap_return_1 <= sin_dds_V_fu_910_p3;
    brmerge40_demorgan_i_1_fu_786_p2 <= (newsignbit_1_reg_1308 and deleted_ones_1_fu_763_p3);
    brmerge40_demorgan_i_fu_726_p2 <= (newsignbit_reg_1289 and deleted_ones_fu_703_p3);
    brmerge40_i1_fu_791_p2 <= (brmerge40_demorgan_i_1_fu_786_p2 xor ap_const_lv1_1);
    brmerge40_i_fu_731_p2 <= (brmerge40_demorgan_i_fu_726_p2 xor ap_const_lv1_1);
    brmerge6_fu_857_p2 <= (ap_pipeline_reg_pp0_iter16_overflow_reg_1321 or underflow_16_not_fu_852_p2);
    brmerge7_fu_892_p2 <= (ap_pipeline_reg_pp0_iter16_overflow_1_reg_1332 or underflow_17_not_fu_887_p2);
    brmerge_i4_fu_715_p2 <= (newsignbit_reg_1289 or p_not_i_fu_710_p2);
    brmerge_i5_fu_775_p2 <= (newsignbit_1_reg_1308 or p_not_i1_fu_770_p2);
    brmerge_i_i4_fu_848_p2 <= (underflow_2_reg_1343 or ap_pipeline_reg_pp0_iter16_overflow_reg_1321);
    brmerge_i_i5_fu_883_p2 <= (underflow_3_reg_1350 or ap_pipeline_reg_pp0_iter16_overflow_1_reg_1332);
    carry_1_fu_753_p2 <= (ap_pipeline_reg_pp0_iter14_tmp_39_reg_1267 and tmp_20_fu_748_p2);
    carry_fu_693_p2 <= (ap_pipeline_reg_pp0_iter14_tmp_32_reg_1241 and tmp_12_fu_688_p2);
    cos_dds_V_fu_875_p3 <= 
        p_Val2_87_mux_fu_862_p3 when (brmerge6_fu_857_p2(0) = '1') else 
        p_Val2_4_9_fu_869_p3;
    dds_0_cos_lut_V_address0 <= tmp_1_fu_174_p1(10 - 1 downto 0);
    dds_0_cos_lut_V_address1 <= tmp_4_fu_183_p1(10 - 1 downto 0);

    dds_0_cos_lut_V_ce0_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_ce)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2))) then 
            dds_0_cos_lut_V_ce0 <= ap_const_logic_1;
        else 
            dds_0_cos_lut_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dds_0_cos_lut_V_ce1_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_ce)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2))) then 
            dds_0_cos_lut_V_ce1 <= ap_const_logic_1;
        else 
            dds_0_cos_lut_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    dds_0_cos_lut_V_load_2_fu_190_p1 <= std_logic_vector(resize(unsigned(p_Val2_4_reg_1001),18));
    dds_0_cos_lut_V_load_fu_187_p1 <= std_logic_vector(resize(unsigned(p_Val2_6_reg_996),18));
    dds_0_fine_lut_V_address0 <= tmp_8_fu_480_p1(9 - 1 downto 0);

    dds_0_fine_lut_V_ce0_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter7, ap_ce)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce) and (ap_const_logic_1 = ap_enable_reg_pp0_iter7))) then 
            dds_0_fine_lut_V_ce0 <= ap_const_logic_1;
        else 
            dds_0_fine_lut_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    deleted_ones_1_fu_763_p3 <= 
        tmp_21_fu_758_p2 when (carry_1_fu_753_p2(0) = '1') else 
        ap_pipeline_reg_pp0_iter14_signbit_1_reg_1254;
    deleted_ones_fu_703_p3 <= 
        tmp_13_fu_698_p2 when (carry_fu_693_p2(0) = '1') else 
        ap_pipeline_reg_pp0_iter14_signbit_reg_1228;

    grp_fu_930_ce_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce))) then 
            grp_fu_930_ce <= ap_const_logic_1;
        else 
            grp_fu_930_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_930_p1 <= OP2_V_cast_fu_504_p1(16 - 1 downto 0);

    grp_fu_941_ce_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_ce)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_ce))) then 
            grp_fu_941_ce <= ap_const_logic_1;
        else 
            grp_fu_941_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_941_p0 <= OP2_V_cast_fu_504_p1(16 - 1 downto 0);
    overflow_1_fu_780_p2 <= (brmerge_i5_fu_775_p2 and tmp_21_fu_758_p2);
    overflow_fu_720_p2 <= (brmerge_i4_fu_715_p2 and tmp_13_fu_698_p2);
    p_Result_11_not_fu_828_p2 <= (ap_pipeline_reg_pp0_iter15_tmp_39_reg_1267 xor ap_const_lv1_1);
    p_Result_2_not_fu_808_p2 <= (ap_pipeline_reg_pp0_iter15_tmp_32_reg_1241 xor ap_const_lv1_1);
    p_Val2_0_i_i1_fu_321_p3 <= 
        p_Val2_74_mux_fu_280_p3 when (sel_tmp2_fu_316_p2(0) = '1') else 
        sel_tmp_fu_309_p3;
    p_Val2_0_i_i_cast_fu_422_p1 <= std_logic_vector(resize(unsigned(p_Val2_0_i_i_reg_1101),18));
    p_Val2_0_i_i_fu_286_p3 <= 
        ap_const_lv17_0 when (ap_pipeline_reg_pp0_iter5_tmp_2_reg_981(0) = '1') else 
        ap_pipeline_reg_pp0_iter5_p_Val2_4_reg_1001;
    p_Val2_10_fu_576_p4 <= ap_pipeline_reg_pp0_iter13_p_Val2_9_reg_1221(42 downto 27);
    p_Val2_11_fu_614_p2 <= std_logic_vector(unsigned(tmp_11_fu_610_p1) + unsigned(p_Val2_10_fu_576_p4));
    p_Val2_14_fu_632_p4 <= ap_pipeline_reg_pp0_iter13_p_Val2_13_reg_1247(42 downto 27);
    p_Val2_15_fu_670_p2 <= std_logic_vector(unsigned(tmp_19_fu_666_p1) + unsigned(p_Val2_14_fu_632_p4));
    p_Val2_1_8_fu_474_p3 <= 
        p_Val2_74_mux_reg_1096 when (sel_tmp20_reg_1152(0) = '1') else 
        sel_tmp26_fu_467_p3;
    p_Val2_1_fu_303_p3 <= 
        ap_const_lv18_20001 when (underflow_1_reg_1076(0) = '1') else 
        ap_pipeline_reg_pp0_iter5_p_Val2_7_reg_1030;
    p_Val2_3_fu_127_p2 <= std_logic_vector(unsigned(incr_V) + unsigned(dds_0_acc_V));
    p_Val2_4_9_fu_869_p3 <= 
        ap_const_lv16_8001 when (underflow_2_reg_1343(0) = '1') else 
        ap_pipeline_reg_pp0_iter16_p_Val2_11_reg_1283;
    p_Val2_5_10_fu_904_p3 <= 
        ap_const_lv16_8001 when (underflow_3_reg_1350(0) = '1') else 
        ap_pipeline_reg_pp0_iter16_p_Val2_15_reg_1302;
    p_Val2_5_fu_193_p2 <= std_logic_vector(unsigned(ap_const_lv18_0) - unsigned(dds_0_cos_lut_V_load_2_fu_190_p1));
    p_Val2_74_mux_fu_280_p3 <= 
        ap_const_lv18_1FFFF when (underflow_reg_1069(0) = '1') else 
        ap_pipeline_reg_pp0_iter5_p_Val2_5_reg_1019;
    p_Val2_77_mux_fu_425_p3 <= 
        ap_const_lv18_1FFFF when (ap_pipeline_reg_pp0_iter6_underflow_1_reg_1076(0) = '1') else 
        ap_pipeline_reg_pp0_iter6_p_Val2_7_reg_1030;
    p_Val2_7_fu_207_p2 <= std_logic_vector(unsigned(ap_const_lv18_0) - unsigned(dds_0_cos_lut_V_load_fu_187_p1));
    p_Val2_87_mux_fu_862_p3 <= 
        ap_const_lv16_7FFF when (brmerge_i_i4_fu_848_p2(0) = '1') else 
        ap_pipeline_reg_pp0_iter16_p_Val2_11_reg_1283;
    p_Val2_8_fu_495_p3 <= 
        ap_pipeline_reg_pp0_iter7_p_Val2_1_reg_1106 when (ap_pipeline_reg_pp0_iter7_sel_tmp20_reg_1152(0) = '1') else 
        sel_tmp18_fu_489_p3;
    p_Val2_91_mux_fu_897_p3 <= 
        ap_const_lv16_7FFF when (brmerge_i_i5_fu_883_p2(0) = '1') else 
        ap_pipeline_reg_pp0_iter16_p_Val2_15_reg_1302;
    p_Val2_s_7_fu_297_p3 <= 
        ap_const_lv18_20001 when (underflow_reg_1069(0) = '1') else 
        ap_pipeline_reg_pp0_iter5_p_Val2_5_reg_1019;
    p_not_i1_fu_770_p2 <= (ap_pipeline_reg_pp0_iter14_signbit_1_reg_1254 xor carry_1_fu_753_p2);
    p_not_i_fu_710_p2 <= (ap_pipeline_reg_pp0_iter14_signbit_reg_1228 xor carry_fu_693_p2);
    qb_assign_1_fu_604_p2 <= (r_i_i_fu_599_p2 and qbit_fu_585_p3);
    qb_assign_3_fu_660_p2 <= (r_i_i1_fu_655_p2 and qbit_1_fu_641_p3);
    qbit_1_fu_641_p3 <= ap_pipeline_reg_pp0_iter13_p_Val2_13_reg_1247(26 downto 26);
    qbit_fu_585_p3 <= ap_pipeline_reg_pp0_iter13_p_Val2_9_reg_1221(26 downto 26);
    r_1_fu_571_p2 <= "0" when (tmp_38_reg_1262 = ap_const_lv26_0) else "1";
    r_fu_566_p2 <= "0" when (tmp_31_reg_1236 = ap_const_lv26_0) else "1";
    r_i_i1_fu_655_p2 <= (tmp_40_fu_648_p3 or r_1_reg_1278);
    r_i_i_fu_599_p2 <= (tmp_33_fu_592_p3 or r_reg_1273);
    sel_tmp10_fu_347_p2 <= (sel_tmp18_demorgan_reg_1090 xor ap_const_lv1_1);
    sel_tmp11_fu_352_p2 <= (tmp_6_reg_1063 and sel_tmp10_fu_347_p2);
    sel_tmp12_fu_357_p2 <= (sel_tmp11_fu_352_p2 and underflow_1_reg_1076);
    sel_tmp13_fu_448_p3 <= 
        p_Val2_0_i_i_cast_fu_422_p1 when (sel_tmp12_reg_1134(0) = '1') else 
        sel_tmp8_fu_442_p3;
    sel_tmp14_fu_362_p2 <= (sel_tmp11_fu_352_p2 and underflow_14_not_fu_292_p2);
    sel_tmp15_fu_484_p3 <= 
        p_Val2_0_i_i_cast_reg_1163 when (ap_pipeline_reg_pp0_iter7_sel_tmp14_reg_1140(0) = '1') else 
        sel_tmp13_reg_1168;
    sel_tmp16_fu_372_p2 <= (sel_tmp33_demorgan_fu_368_p2 xor ap_const_lv1_1);
    sel_tmp17_fu_378_p2 <= (ap_pipeline_reg_pp0_iter5_tmp_2_reg_981 and sel_tmp16_fu_372_p2);
    sel_tmp18_demorgan_fu_269_p2 <= (tmp_s_fu_229_p2 or tmp_3_fu_234_p2);
    sel_tmp18_fu_489_p3 <= 
        ap_pipeline_reg_pp0_iter7_p_Val2_1_reg_1106 when (ap_pipeline_reg_pp0_iter7_sel_tmp17_reg_1146(0) = '1') else 
        sel_tmp15_fu_484_p3;
    sel_tmp19_fu_388_p2 <= (sel_tmp42_demorgan_fu_383_p2 xor ap_const_lv1_1);
    sel_tmp1_fu_264_p2 <= (ap_pipeline_reg_pp0_iter4_tmp_2_reg_981 xor ap_const_lv1_1);
    sel_tmp20_fu_394_p2 <= (underflow_12_not_fu_275_p2 and sel_tmp19_fu_388_p2);
    sel_tmp21_fu_400_p3 <= 
        ap_pipeline_reg_pp0_iter5_dds_0_cos_lut_V_load_2_reg_1014 when (sel_tmp9_fu_329_p2(0) = '1') else 
        p_Val2_s_7_fu_297_p3;
    sel_tmp22_fu_407_p3 <= 
        ap_pipeline_reg_pp0_iter5_dds_0_cos_lut_V_load_reg_1007 when (sel_tmp5_fu_338_p2(0) = '1') else 
        sel_tmp21_fu_400_p3;
    sel_tmp23_fu_414_p3 <= 
        ap_const_lv18_0 when (sel_tmp7_fu_343_p2(0) = '1') else 
        sel_tmp22_fu_407_p3;
    sel_tmp24_fu_455_p3 <= 
        p_Val2_1_reg_1106 when (sel_tmp12_reg_1134(0) = '1') else 
        sel_tmp23_reg_1158;
    sel_tmp25_fu_460_p3 <= 
        p_Val2_77_mux_fu_425_p3 when (sel_tmp14_reg_1140(0) = '1') else 
        sel_tmp24_fu_455_p3;
    sel_tmp26_fu_467_p3 <= 
        ap_const_lv18_0 when (sel_tmp17_reg_1146(0) = '1') else 
        sel_tmp25_fu_460_p3;
    sel_tmp2_fu_316_p2 <= (underflow_12_not_fu_275_p2 and sel_tmp1_reg_1084);
    sel_tmp33_demorgan_fu_368_p2 <= (sel_tmp18_demorgan_reg_1090 or tmp_6_reg_1063);
    sel_tmp3_fu_431_p3 <= 
        ap_pipeline_reg_pp0_iter6_dds_0_cos_lut_V_load_reg_1007 when (sel_tmp9_reg_1119(0) = '1') else 
        p_Val2_1_reg_1106;
    sel_tmp42_demorgan_fu_383_p2 <= (sel_tmp33_demorgan_fu_368_p2 or ap_pipeline_reg_pp0_iter5_tmp_2_reg_981);
    sel_tmp4_fu_333_p2 <= (tmp_s_reg_1051 xor ap_const_lv1_1);
    sel_tmp5_fu_338_p2 <= (tmp_3_reg_1058 and sel_tmp4_fu_333_p2);
    sel_tmp6_fu_436_p3 <= 
        p_Val2_0_i_i1_reg_1114 when (sel_tmp5_reg_1124(0) = '1') else 
        sel_tmp3_fu_431_p3;
    sel_tmp7_fu_343_p2 <= (tmp_s_reg_1051 and ap_pipeline_reg_pp0_iter5_tmp_2_reg_981);
    sel_tmp8_fu_442_p3 <= 
        ap_pipeline_reg_pp0_iter6_dds_0_cos_lut_V_load_reg_1007 when (sel_tmp7_reg_1129(0) = '1') else 
        sel_tmp6_fu_436_p3;
    sel_tmp9_fu_329_p2 <= (tmp_s_reg_1051 and sel_tmp1_reg_1084);
    sel_tmp_fu_309_p3 <= 
        ap_const_lv18_0 when (ap_pipeline_reg_pp0_iter5_tmp_2_reg_981(0) = '1') else 
        p_Val2_s_7_fu_297_p3;
    sin_adr_V_fu_169_p2 <= std_logic_vector(unsigned(ap_const_lv10_0) - unsigned(lsb_V_reg_959));
    sin_dds_V_fu_910_p3 <= 
        p_Val2_91_mux_fu_897_p3 when (brmerge7_fu_892_p2(0) = '1') else 
        p_Val2_5_10_fu_904_p3;
    tmp9_fu_838_p2 <= (tmp_22_fu_833_p2 and tmp_24_reg_1338);
    tmp_11_fu_610_p1 <= std_logic_vector(resize(unsigned(qb_assign_1_fu_604_p2),16));
    tmp_12_fu_688_p2 <= (newsignbit_reg_1289 xor ap_const_lv1_1);
    tmp_13_fu_698_p2 <= (ap_pipeline_reg_pp0_iter14_signbit_reg_1228 xor ap_const_lv1_1);
    tmp_14_fu_813_p2 <= (ap_pipeline_reg_pp0_iter15_newsignbit_reg_1289 or p_Result_2_not_fu_808_p2);
    tmp_15_fu_737_p2 <= "1" when (tmp_35_reg_1297 = ap_const_lv15_0) else "0";
    tmp_16_fu_742_p2 <= (tmp_15_fu_737_p2 or brmerge40_i_fu_731_p2);
    tmp_17_fu_521_p3 <= (ap_pipeline_reg_pp0_iter10_p_Val2_1_8_reg_1173 & ap_const_lv25_0);
    tmp_19_fu_666_p1 <= std_logic_vector(resize(unsigned(qb_assign_3_fu_660_p2),16));
    tmp_1_fu_174_p1 <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter1_lsb_V_reg_959),32));
    tmp_20_fu_748_p2 <= (newsignbit_1_reg_1308 xor ap_const_lv1_1);
    tmp_21_fu_758_p2 <= (ap_pipeline_reg_pp0_iter14_signbit_1_reg_1254 xor ap_const_lv1_1);
    tmp_22_fu_833_p2 <= (ap_pipeline_reg_pp0_iter15_newsignbit_1_reg_1308 or p_Result_11_not_fu_828_p2);
    tmp_23_fu_797_p2 <= "1" when (tmp_42_reg_1316 = ap_const_lv15_0) else "0";
    tmp_24_fu_802_p2 <= (tmp_23_fu_797_p2 or brmerge40_i1_fu_791_p2);
    tmp_27_fu_221_p1 <= p_Val2_5_fu_193_p2(17 - 1 downto 0);
    tmp_28_fu_225_p1 <= p_Val2_7_fu_207_p2(17 - 1 downto 0);
    tmp_2_fu_178_p2 <= "1" when (ap_pipeline_reg_pp0_iter1_lsb_V_reg_959 = ap_const_lv10_0) else "0";
    tmp_31_fu_539_p1 <= grp_fu_930_p3(26 - 1 downto 0);
    tmp_33_fu_592_p3 <= ap_pipeline_reg_pp0_iter13_p_Val2_9_reg_1221(27 downto 27);
    tmp_35_fu_628_p1 <= p_Val2_11_fu_614_p2(15 - 1 downto 0);
    tmp_38_fu_556_p1 <= grp_fu_941_p3(26 - 1 downto 0);
    tmp_3_fu_234_p2 <= "1" when (ap_pipeline_reg_pp0_iter4_msb_V_reg_952 = ap_const_lv2_1) else "0";
    tmp_40_fu_648_p3 <= ap_pipeline_reg_pp0_iter13_p_Val2_13_reg_1247(27 downto 27);
    tmp_42_fu_684_p1 <= p_Val2_15_fu_670_p2(15 - 1 downto 0);
    tmp_4_fu_183_p1 <= std_logic_vector(resize(unsigned(sin_adr_V_reg_971),32));
    tmp_5_fu_244_p2 <= "1" when (tmp_27_reg_1041 = ap_const_lv17_0) else "0";
    tmp_6_fu_239_p2 <= "1" when (ap_pipeline_reg_pp0_iter4_msb_V_reg_952 = ap_const_lv2_3) else "0";
    tmp_7_fu_254_p2 <= "1" when (tmp_28_reg_1046 = ap_const_lv17_0) else "0";
    tmp_8_fu_480_p1 <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter6_p_Result_8_reg_966),32));
    tmp_9_fu_510_p3 <= (ap_pipeline_reg_pp0_iter10_p_Val2_8_reg_1184 & ap_const_lv25_0);
    tmp_fu_818_p2 <= (tmp_14_fu_813_p2 and tmp_16_reg_1327);
    tmp_s_fu_229_p2 <= "1" when (ap_pipeline_reg_pp0_iter4_msb_V_reg_952 = ap_const_lv2_0) else "0";
    underflow_12_not_fu_275_p2 <= (underflow_reg_1069 xor ap_const_lv1_1);
    underflow_14_not_fu_292_p2 <= (underflow_1_reg_1076 xor ap_const_lv1_1);
    underflow_16_not_fu_852_p2 <= (underflow_2_reg_1343 xor ap_const_lv1_1);
    underflow_17_not_fu_887_p2 <= (underflow_3_reg_1350 xor ap_const_lv1_1);
    underflow_1_fu_259_p2 <= (isneg_1_reg_1036 and tmp_7_fu_254_p2);
    underflow_2_fu_823_p2 <= (tmp_fu_818_p2 and ap_pipeline_reg_pp0_iter15_signbit_reg_1228);
    underflow_3_fu_843_p2 <= (tmp9_fu_838_p2 and ap_pipeline_reg_pp0_iter15_signbit_1_reg_1254);
    underflow_fu_249_p2 <= (isneg_reg_1025 and tmp_5_fu_244_p2);
end behav;
