# This file was generated by WriteXDCFile from collected XDCAnnotations.

create_generated_clock -name BaseClock -source [get_pins -of [get_clocks host_clock]] [get_pins -hierarchical -regexp .*WRAPPER_INST/CL/firesim_top/top/sim/target/GCD__/RationalClockBridge_clocks_0_buffer/O.*] -divide_by 1
set_multicycle_path 1 -setup -from [get_clocks BaseClock] -to [get_clocks BaseClock]
set_multicycle_path 0 -hold  -from [get_clocks BaseClock] -to [get_clocks BaseClock]
