// Amazon FPGA Hardware Development Kit
//
// Copyright 2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Amazon Software License (the "License"). You may not use
// this file except in compliance with the License. A copy of the License is
// located at
//
//    http://aws.amazon.com/asl/
//
// or in the "license" file accompanying this file. This file is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, express or
// implied. See the License for the specific language governing permissions and
// limitations under the License.
`pragma protect begin_protected
`pragma protect version = 1
`pragma protect encrypt_agent = "XILINX"
`pragma protect encrypt_agent_info = "Xilinx Encryption Tool 2015"
`pragma protect key_keyowner = "Xilinx", key_keyname = "xilinxt_2017_05", key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 76, bytes = 256)
`pragma protect key_block
p7YWHJdTJ/xVr6XCXgE7YjYfbZeywbdBgTmrgIke9OosPlxejL8GGvrfW1kg6ZnXi7J9QjIt6+Wa
HqJOSlLvEELIynaPWDISveakb6UhKUEsmqldAufliOIthEZW6ir88EfHIptFrJaYoV9ARg6jDCEi
e3PQjbhhfZMLwKv4/X51by7nsYEA7dTAVU82TxuPdSEg6bPpHfjeGEYkHXrx5yq7a/4V3ebKqbTa
o+t2XmgOsElg4hLgkwrjBxLouODCukYAUdCpd+/q6J0sPHMZ7oDL4h1uJh1nyC8GY5llqxyX7xu4
g3t2DFLFT4h6TtRAT1Bq45JPYXGRDqz8IL2iyA==

`pragma protect key_keyowner = "Synopsys", key_keyname = "SNPS-VCS-RSA-1", key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 76, bytes = 128)
`pragma protect key_block
EYLBpIrjAhaSoaHEV18H/nfywYcwXH9hpdSarFtz6dwOQdRD2jKVM0UysNOvjan18eNCZH0078wz
hH7rtU2nODlKMj+pdI+IKM2BLezj9qy+sVFLDEEZrjASaYufcwARGT+M90A/6pjCxrSWNFfL4F5W
uQaVKLOZGW6RG+h9gjA=

`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-1", key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 76, bytes = 128)
`pragma protect key_block
O+09o5p/VbQ4ii4siVHDg4PuC3rZXWnxQDjnYpvty2ScA9rKeBkn+8BWkR8x91TY5MeXskoR383A
5zy3GM5z7tukxOyd6j02FM3jHmjWE0i+IAxdMUFV6mK0OURKkVgzsJJA7jnaDSyqR9T+LmHBvG0L
iFxtGTqLQmJFCxIFafY=

`pragma protect key_keyowner = "Cadence Design Systems.", key_keyname = "cds_rsa_key", key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 76, bytes = 64)
`pragma protect key_block
fLS2O3kT5Hsg654W7mlbECgTNdyd8/S7yV690qanQ9wBIUhXZ1q0syfZU5kIHcbNa5vUcu5ig72s
35q5oqv4cA==

`pragma protect data_method = "AES128-CBC"
`pragma protect encoding = (enctype = "BASE64", line_length = 76, bytes = 2048)
`pragma protect data_block
U9AyKwkgHDjRMhJ1Vab7WnjttpnMFXV8aHZflI+A9H4vO75zK9mxhlVYrwuAB7Di86qQRMgBqEXK
UI/bZfV6hHH2x3amx8+guI0vkw2fLOYiRXXTnJP9iBG3NGxlPIL2krkdggt1ko9NQz5hQfPqiQoS
nxsxF6XoarrzBSRboA9crWhI5wXT3YDc60sjfLl4bP19fiiip3i6Hfr6h3h39R20OYALoAbXba87
CDDB2UKoHnUP+7uvERgaCzb9JuB2uftmrNAFhOjwAsTSKnppHgbfNw73TRZaE6NqWVfMDRLJmvRz
b9j70NZJ7A7mwzcMwUDNppH+7Xe0mJSZXgapZ52reXjQHIdYihoIt2gu0wYvsyh4HA/3cP+nt4fc
Jhua9u/lh9PGCiVgIDU3V7siXAxfAx6vU9Z5VZfY6UQwttU49TFTrqRfjqwVGw0cB9hwg/q7zcpr
VZXubzI75ci5i7QyHIo74yMq8yBTdqnTPW2JCiXih44w1e6lrfY5oKFY8IadKThSk+5kBwsvqrqa
BRWJ5fVTmyyjwWQhJgnEqhbO7uC/5plbbzKaq6Fsqiwv1JJGQo/x12YRBwTZEJe6I5JuR/MrYmln
nyTqlLAIEIdlvDblZ3IBCuGujJfs+aQaDZLMiES1mFpJ1iLJPVG47XdgTdt1JE7YVXV7/3Q9inNt
k7sQKEkBFSDCNvX8EFOFeyjqedy3nm9xduPguRvc+6JHYPCIUW6z4kBMfpISMwIjQQobacCsm9ca
OeBOzCK7nsImC5YeE+gCThZSVBdFdUiOPuF5mD9adJ+eOlaV0xBscnaus6FOp8ytsF/GCxItMX0T
2c4/X0lNtAbep42ZhUB+rsbM+gzaMMR/ADa+MeIdWVZyCdVjvbRNV8VdTG382Ezl9lJY8k+DbgNK
2RwVS0sS/Sw/cOaeuRiv9HvcOAoPkeVF1u6it862AmDXFQH70FKdpwYust2EQU0c+cpUZYHK3oDG
YzKB8xhmcXoKkmfeO8HaeI0c05BwMV/OCPNMGHlqxlF3s0UB3QndZkLtOaZM23uBKoJpfkXYLE64
50uNQwcSdH/6Qzo/YLWqntcxYiSXs++P2/w/0YOmnkd6IDvt4yQ9q3dkEO5vTqNKDGl5IMriXKSZ
J4xRM1MDuO6sd1K15XQkLFgf2JEdFK0aRDr53ZAIbHsE8i66/QaB6Ze3jwTw3ekeCraBlj7YEp6S
6BJpmO64YlZLeE+lZHhqY4Vcc+VajVjw0v743flv3H73EnV5wpg0TQMxZOPepe09VJ6D2WQLfWwU
2jMohJ9+krwi5duIqOSCWG8Kz1YZvpnrSWP0iCw8YruXA2MVgQEj+hT312Voc+mWdFPvvE8d9k+Q
OPScjZ/ZdfbSlp6fJtdUNf/77tuch9H+1iWZjJWWJwBhVQgWcm+/TK9OlTzar+S1zBikgQTOvsCJ
2aDanfj7YeM2ikeG9BwOlCIn+1iYwJWz8IwVOhXi4IOlfA4y3UFpGtjHVfikrr+RIFegIWCvy06z
g0W2sMxr6Drlqh3MC6RukhWUk2Ko9vmhYUCMRJzPz5lmjAW8Pj9jA0Io3A2FgeYBxrHXJb/vek9y
chgeu2ri24gpbeeAN/8ZSxfs50Af1wg/3a0ndib/MIapVK5RHXMMNpgLPe61nyF7N1SGsdx6ktOx
d9bJGM7d3zk2E1LUjXxSwLcEOo+N5tCKvB8+8ar3WSTWUKyyszmaBjLnNUnZYBxGdCijwzylC9sA
oLFoHbvCP4qgq6Y/bgNzMr5v5FFXubI8epAZoFjFTy0mc12ZMONMaSBWp4gDAQ9AkRYlz1jQ+FYZ
T6uPIva3iXrlAqb9NYFYl4p6Kc+szazYDpn4WVlAo5ZkxMvaKaAcwnzudVNGHBMADgHBzCEA1hPS
QP91AdfjQi9ygqlV+XMBjc0tD3jghnAC+aXTxTB6DuQTRDEfwq+s+h3HoPBarIOzNtOCQ0vGFgEh
dnmicDRLwy+l0/dJHB41EMh8DR87mIIbGu4FGstY6OsEd0g36OKLQMbu1Wv484VYuHqbOS6c/EoT
yYgqrBjelWIAQ+chbI7VtXAxjgXrkvn9JvJS6D9YtzzRe9fJpA7OqeI/av8+nYEYWRe6vJtK3JWs
zBWSFZB6AxZwCq7TAWEeRuEwW96a+2hjLT3dtxxxd7xhudhyK7nn15DILhSE5OlIlI54XHTXWezO
o9xnA3Ejg7sTBlQgCukPN9I6jI6umCyLHtmAcYQASZIskwM+TjJgt8PRazsajXfycFep7roVv5jg
45wKu6MDZ+khRLhZQR7ngR0zzXR98wmWwQSvvDo5YLJP8U/vevn4dzhRB9IkMP/zcUCB/oNCt4P5
4r3zn7LkNV59c+cTbfQSkYXZ+cgd4H5HKnydVhU5PQYV5YPxDFdz9F7GMhfXatw9WvPGYjcNirRy
z47BdiDDLHaPYtxR92AtXNYXRKN6beFuaarWYLT2GCtn6UWJqahfgmivcXk/xwPfItloSy+sU355
HL/JRZJLWR0n+Ya0qvl25Q4DTOdyjXbMOI+rU1hko+R5lGIQmSDoDVqiVxY1ZR1g4V8ZcREhjius
LRezt1SS0Hqk641qUpFVqqXhdUvoxcDvizyDl9EDHbX0nvhG+S0w+GiYF2AlmSxyAEsdQ1DMNbKa
fk9bDV/qYjDaJGBbPWvRuOR2C1PQYp96PeUGPmB2VzTr0k7lScwVAJa/IT0Td8C7XRxrzkg=
`pragma protect end_protected
