// Amazon FPGA Hardware Development Kit
//
// Copyright 2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Amazon Software License (the "License"). You may not use
// this file except in compliance with the License. A copy of the License is
// located at
//
//    http://aws.amazon.com/asl/
//
// or in the "license" file accompanying this file. This file is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, express or
// implied. See the License for the specific language governing permissions and
// limitations under the License.

// SHA: bddf8457046b3a64e63d28d7e334020b6f1d09ee
`pragma protect begin_protected
`pragma protect version = 1
`pragma protect encrypt_agent = "XILINX"
`pragma protect encrypt_agent_info = "Xilinx Encryption Tool 2015"
`pragma protect key_keyowner = "Xilinx", key_keyname = "xilinxt_2017_05", key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 76, bytes = 256)
`pragma protect key_block
YRd121jA5r71rMS0Qfp0nbpzqvfqAB+9ZW4z0WuuTMVIyrDmdZhGQfSNpbF5FNc1oH8Cp4yO0pDe
+0R6ke40eI2VfzjJpKhI/X9VB71mJzNQkodcLDse/nOGdipdYNPsD4kzOmfgsfM0gQLi5TwmXplf
1BH6jeNx5wCJ/A5q8N1DBeeTTyyT1RU6x+ntb1kPEW7RCnKgG3puPMRmGjKtZB5OXdmvJcxDypbS
IFCvlosCIhTb9ZHe8/hQJyfLlRYdzCaDOfZs83xyePIsGf29RlMCVjnbeA6LwImlnNMLQv1+m0YY
bJhC2ws87B/TFA+lQU5mSab0rE8HJTgg0qC8JA==

`pragma protect key_keyowner = "Synopsys", key_keyname = "SNPS-VCS-RSA-1", key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 76, bytes = 128)
`pragma protect key_block
kl+Ju9yPnlp/yDL6cZ8JAEaFrt4wlUfk5Pgvyxl/q2w41EkHBjllyzU2pI7NgCtQDMl00W+Ulfdj
tk6Wimpmd3mMUZqLVF4msgjJkFPHzOvJoGjpKqTyLqG/zJNod09TPwz9NGCceYcb3LI5OcMQP925
ifP75YMB1HJj096AOAU=

`pragma protect key_keyowner = "Mentor Graphics Corporation", key_keyname = "MGC-VERIF-SIM-RSA-1", key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 76, bytes = 128)
`pragma protect key_block
SVGMtA7pFPDlZPf841vcR+hZ1Gp3Rah+MH/BaP0S+lAen6VcBraQKDiHAtJDIi6s/RH/4nZtnRmo
o4e1/R3fQaSRsMEePwOE6UqBGuGywe8f4ECUQO6u/rdvFhZl34UaSZkMX/fMBE3btWRWqqB3u6cl
w4KSHcZNq1zR269WEVY=

`pragma protect key_keyowner = "Cadence Design Systems.", key_keyname = "cds_rsa_key", key_method = "rsa"
`pragma protect encoding = (enctype = "BASE64", line_length = 76, bytes = 64)
`pragma protect key_block
RmSmLnmDlsHVxlIVnJK/cDqGa7wwDKBlua0Raekq1MJT2HxzVooA31ms2Zpf3xne1j78oNfk9aLs
lqC87wfimQ==

`pragma protect data_method = "AES128-CBC"
`pragma protect encoding = (enctype = "BASE64", line_length = 76, bytes = 2048)
`pragma protect data_block
pOabQwlCsY3uP+Cs+4UL4HjesObj565OzS8YrMNq/XpqlGX4rb4Yz4pd26geb3P/TTXRAW9DOAV9
GcMv8Yk1SBnk1BDE0z46BHsqwAn3cak2L8XJdZhxN3jtzXLEfAs5rfrxOYlFDYqMG93NcNE/D9mJ
PfpOTR8PvS2u3crEf4RQe6tO8hpbz7Ml4wfNJoQBczl3OvJHWhvoNtLpt3nGWeDP9qxO8ewgl/Ho
Psz8AHRrrMnS9nFUhG5/bA9M4er22rBgAhi3tKweSkcbSHAMxjzObwUGskblJey2I8PdkOueP5Pb
okDt+eyyZshyQlH6c74WkFAk7Chg1QcFAOeNrsA8ofvV210QZF1sToEBTJtdZSWl0JLMtBMQ/rQD
8DVbjGsmqZO0Ua9d0cczsiA2bvrMsOAMKoii7d3BLQ8naqMi9iG8O4fQ288bJR31iaauZztwOZIC
m/vP5aVw8mtcnLInYU3W4a4FcKdyyDorzWervsMQfFqpClFn2OQsQpcxie2z3KjIZ6BpmdCeXlCO
gkiefW1dUv9m0t2JmuLCzgoOCaZeuuKkxifupMVc2/rrjQTEVqACIRlfxW1KmBi0kHQWDV6qeNn7
4psHJlGi3EiW1eZ23ZXFtjkUgV4BRgJ8wKVnoKgnWQj9/u30NG6hvNS6RVyFoumpqxBlulOTU4+b
N+E7qE3zH86PF9oMbHmMR6x8VPrO5BM7W1+6Ro2SmCgbOGHOIbFcvoAhx4IKjdZnKJiJ3xPHqzgj
ElLq2QDhryHQMH4reuWYrhHqnf1FsFPG06yras/auoNR+NRJz8+lhsGj0H4YWVFExO2m2dmlVkSh
p+D0EhWZtMNulnm3u7cbVEhAUXcrt4EnfigZBrNXsnobSfNCuLAxQgZHWgRI49hgg2qTscHaIdtK
L/VJenQsCJdsU+xvZR8VLn+SK6wgCVmOeBCJtjkEfiknPaXADxuxyA9G8O03DbM0qO59MvOs8taV
cHU4p1mJt+5qdl5W3SbPzlvnJOzD+1xCZLJ08f6yfHkwKXM4ZgrDiTsU4JqXo+yDHsUTIumCpTcT
O1+H6qqRte8y3ZNczqTOihxMl8wZwdOVPNA/IiVhD6p0UGLs5idMdAZvdeFnoaxhgP9Z+vFHvNQy
oxtzPZKfTyis1w+3HQfree3kuTeptfmblZ8dZzo2ChqX8n20ya/yqDGx/XhdBp4IR/4u378u2Pnw
HDb/CjYy5ofCFiOL1K6LbFzUscbO+b5gMxSgS/O5dpSQx06ZlU16HU6H0DJeqrR4FV0OvF05NtDL
BVayHy9E/BPSPuoAjyMAuKssMJKqRezHOBSNBSV7dQZuDPXyzqI9AV02eSCL8cLrxO45a0fCb693
WDGVcajeN+o7MRl2uN2vcp6VC0nLjmxfgqCVfo7219KqUs3kSd33+rBUfrsQCJDIpY3GAuTltKRa
IApifVEWCKodorb/jesRD53C+BBJigHThLfCzyA+jd5A8Vyb3BKYuJhTA9ZYfGet5TpgLs+NlTxq
hP699ccdXex+/o8+ttWRoC35II8zCe9p7t9qfkVmqS+4jG8RwaXCuewYY5OVyqVMDDOY5XUPL/9M
Bn5KnR4Z+egdTZhcDjLAuTOYgGsCvVIb6c0hAcpY7tb1EG9nOUz4j0AE7ap9Gc1cW1f911SYMfgF
3D9eYb1VVcIHvvF2L0ytE3E9LbR2Ltio/Iuf9EFeNGCUxfjAx3RANs0n9iYAPjvIWwJxX7NRqcKk
EFbYNL4qeiiHeBcCWafsjbFknkFP8hFizIIwHkscH2DPQpdVMwhfbn2l6F8sd+zC5GsOQpe5+O24
Waf0v8ESo7rPzOjFLgKKsqIS4EGbaBplvHOALJXDZ2upEZVyBHHpYQN0wfcIXPl1lZ9J46nvP4tb
Yk9jaoWSQJsTTDPVx4EDqeiq+ct4kqcQ7en3TpiJgA2stDKPURsoGmxS3IWwHq0apqXXM/b6r+1z
XBDCpSIMoqomb1frZjlMJ3Rtz86DPp13v3LeLur2oQjCtlVqZeCLx9wnZ9KwOTDWo+2Dl31S0pTh
K7REfP0xFmfVYBOcHrkbo6xwgQxOOpFmqQQHzMTA8igKaqnNT/xj4MkrxOGVWIaYq98dPpnV+S2j
SS6OqegcU/1rwy7XyT71wqdXeocjXAmKQC78yQOwLJvfOicha3B1TovCgO2sN9bqu04ATLsDS33H
qP/hEmkkZNBHvrWpChmCiCqpeQQnOEeZuC+RarkbqK+sSGSAOtVrtwL1ufr43pBDcr7Me3ocrCJm
bo51yhV85ImLoDeFGZBUoxx4EWTvVe6lV+b7p1sQyGq7t4RD9nXq/8y9httiECXDl6lD8GHtT28I
vqdQm13++rnjdbHkb0a0ekLdgndoDefD5PkNSdoRU+N3dhYCfZTbJXApfVT+M+3EyXnvEmS4uNjj
Z4OqzneMiVT4jsTvUavW+uiReLEaxD9MCYWxRXnhzs+INJ3/XUxT3cDzhBHhlwQ+JwW3t4pHWpu3
8HJpkLTL8rqWo6ctBEuxjSUXYCpbJ6Dpv0iSfvhq8NN36v/J6PBBU74Y6n/AANodq4GxOjFTATzc
hsh2qQrqSzFwVzQpIZl9Cztj6uGy+0f0od+fvYQKgMfZxfRR1xz53vU6CCVGifmAkcxLIOoY6Ku/
lFht37FyXvmCCyz0hGEZQiaM2R43p3cST2hSbxpDkg4zKVPP6HSUV/sYwgGfjRXlSM4Xolk=
`pragma protect end_protected
