/*
 * Copyright 2025 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"). You may
 * not use this file except in compliance with the License. A copy of the
 * License is located at
 *
 *     http://aws.amazon.com/apache2.0/
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */

#pragma once

#define SDE_SET_BITFIELD(BITFIELD, VALUE, PTR) \
    *(PTR) &= ~(BITFIELD ## _MASK); \
    *(PTR) |= ((VALUE << BITFIELD ## _SHIFT) & BITFIELD ## _MASK);

#define SDE_GET_BITFIELD(BITFIELD, VALUE) \
    ((VALUE & BITFIELD ## _MASK) >> BITFIELD ## _SHIFT)

#define C2H_NUM_MD_IN_RING 64
#define SDE_NUM_DESC 64

struct c2h_desc {
  uint32_t length;
  uint64_t phys_addr;
  uint32_t reserved;
} __attribute__((packed));

struct c2h_wb_metadata {
  uint32_t length;
  uint32_t status;
  uint64_t user;
} __attribute__((packed));

#define METADATA_STATUS_VALID_MASK 0x1
#define METADATA_STATUS_VALID_SHIFT 0
#define METADATA_STATUS_EOP_MASK 0x2
#define METADATA_STATUS_EOP_SHIFT 1

struct h2c_desc {
  uint32_t length;
  uint64_t phys_addr;
  uint32_t cfg_bits;
  uint64_t reserved;
  uint64_t user;
} __attribute__((packed));

#define DESC_CFG_BITS_EOP_MASK 0x1
#define DESC_CFG_BITS_EOP_SHIFT 0
#define DESC_CFG_BITS_SPB_MASK 0x2
#define DESC_CFG_BITS_SPB_SHIFT 1

struct c2h_status {
  uint32_t status;
  uint32_t desc_limit;
  uint32_t desc_completed;
  uint32_t pkt_completed;
  uint32_t meta_write;
} __attribute__((packed));

struct h2c_status {
  uint32_t status;
  uint32_t desc_limit;
  uint32_t desc_completed;
  uint32_t pkt_completed;
} __attribute__((packed));

#define STATUS_DESC_ERR_MASK 0x1
#define STATUS_DESC_ERR_SHIFT 0
#define STATUS_DM_ERR_MASK 0x2
#define STATUS_DM_ERR_SHIFT 1
#define STATUS_WB_ERR_MASK 0x4
#define STATUS_WB_ERR_SHIFT 2

/* ATG and General Configuration Registers */
#define SDE_ATG_CTRL_BASE_REG GLOBAL_ATG_OFFSET
#define SDE_ATG_TX_CTRL_REG (0x0 + SDE_ATG_CTRL_BASE_REG)

#define SDE_ATG0_DATA_REG (0x4 + SDE_ATG_CTRL_BASE_REG)
#define SDE_ATG0_SIZE_REG (0x8 + SDE_ATG_CTRL_BASE_REG)

#define SDE_ATG1_DATA_REG (0xC + SDE_ATG_CTRL_BASE_REG)
#define SDE_ATG1_SIZE_REG (0x10 + SDE_ATG_CTRL_BASE_REG)

#define SDE_RX_CONTROL_REG (0x180 + SDE_ATG_CTRL_BASE_REG)
#define RCR_LOOPBACK_EN_MASK 0x0000001
#define RCR_LOOPBACK_EN_SHIFT 0
#define RCR_BACKPRESSURE_EN_MASK 0x00000010
#define RCR_BACKPRESSURE_EN_SHIFT 4

#define SDE_GENERAL_PURPOSE_CFG_REG (0x2000 + SDE_ATG_CTRL_BASE_REG)
#define GPCR_SDE_RESET_MASK 0x00000001
#define GPCR_SDE_RESET_SHIFT 0
#define GPCR_LOOPBACK_MASK 0x00000002
#define GPCR_LOOPBACK_SHIFT 1
#define GPCR_ARID_INC_MASK 0x00000004
#define GPCR_ARID_INC_SHIFT 2
#define GPCR_ATG_EN_MASK 0x00000008
#define GPCR_ATG_EN_SHIFT 3


/* SDE REGISTERS */
/* PF0, BAR4*/
#define SDE_BASE_ADDR GLOBAL_SDE_OFFSET

/* C2H Descriptor RAM */
#define SDE_C2H_DESC_RAM_MAP_OFFSET (0x0 + SDE_BASE_ADDR)

/* H2C Descriptor RAM */
#define SDE_H2C_DESC_RAM_MAP_OFFSET (0x1000 + SDE_BASE_ADDR)

/* Configuration Registers */
#define SDE_CONFIG_REG_MAP_OFFSET (0x3000 + SDE_BASE_ADDR)

/* PCIS CSRs */
#define SDE_PCIS_CSRS_REGS_OFFSET (0x0 + SDE_CONFIG_REG_MAP_OFFSET)

#define SDE_SW_RESET_REG (0x0 + SDE_PCIS_CSRS_REGS_OFFSET)
#define SWRR_SW_RST_MASK 0x1
#define SWRR_SW_RST_SHIFT 0

#define SDE_INFO_REG (0x4 + SDE_PCIS_CSRS_REGS_OFFSET)
#define SDEIR_C2H_PRESENT_MASK 0x1
#define SDEIR_C2H_PRESENT_SHIFT 0
#define SDEIR_H2C_PRESENT_MASK 0x10000
#define SDEIR_H2C_PRESENT_SHIFT 16

/* PCIM CSRs */
#define SDE_PCIM_CSRS_REGS_OFFSET (0x200 + SDE_CONFIG_REG_MAP_OFFSET)

/* C2H CSRs */
#define SDE_C2H_CSRS_REGS_OFFSET (0x400 + SDE_CONFIG_REG_MAP_OFFSET)

#define SDE_C2H_GLOBAL_CSRS_REGS_OFFSET (0x0 + SDE_C2H_CSRS_REGS_OFFSET)

#define SDE_C2H_DESCRIPTOR_CSRS_REGS_OFFSET (0x100 + SDE_C2H_CSRS_REGS_OFFSET)

#define SDE_C2H_DESCRIPTOR_CREDIT_CONSUMED_COUNTER_REG (0X0 + SDE_C2H_DESCRIPTOR_CSRS_REGS_OFFSET)

#define SDE_C2H_DESCRIPTOR_CREDIT_LIMIT_COUNTER_REG (0X4 + SDE_C2H_DESCRIPTOR_CSRS_REGS_OFFSET)

#define SDE_C2H_COMPLETED_DESCRIPTOR_COUNTER_REG (0X8 + SDE_C2H_DESCRIPTOR_CSRS_REGS_OFFSET)

#define SDE_C2H_DESCRIPTOR_FIFO_PTRS_REG (0XC + SDE_C2H_DESCRIPTOR_CSRS_REGS_OFFSET)
#define C2H_DFPR_FIFO_WR_PTR_MASK 0X7FFF
#define C2H_DFPR_FIFO_WR_PTR_SHIFT 0
#define C2H_DFPR_FIFO_WR_PTR_MSB_MASK 0X8000
#define C2H_DFPR_FIFO_WR_PTR_MSB_SHIFT 15
#define C2H_DFPR_FIFO_RD_PTR_MASK 0X7FFF0000
#define C2H_DFPR_FIFO_RD_PTR_SHIFT 16
#define C2H_DFPR_FIFO_RD_PTR_MSB_MASK 0X8000000
#define C2H_DFPR_FIFO_RD_PTR_MSB_SHIFT 31

#define SDE_C2H_DESCRIPTOR_RAM_ADDR_REG (0X10 + SDE_C2H_DESCRIPTOR_CSRS_REGS_OFFSET)
#define C2H_DRAR_DESC_RAM_ADDR_MASK 0XFFFF
#define C2H_DRAR_DESC_RAM_ADDR_SHIFT 0
#define C2H_DRAR_DESC_RAM_DW_IDX_MASK 0XF0000
#define C2H_DRAR_DESC_RAM_DW_IDX_SHIFT 16

#define SDE_C2H_DESCRIPTOR_RAM_DATA_REG (0X14 + SDE_C2H_DESCRIPTOR_CSRS_REGS_OFFSET)

#define SDE_C2H_DESCRIPTOR_RAM_STATUS_REG (0X18 + SDE_C2H_DESCRIPTOR_CSRS_REGS_OFFSET)
#define C2H_DRSR_DESC_OFLOW_MASK 0X1
#define C2H_DRSR_DESC_OFLOW_SHIFT 0
#define C2H_DRSR_DESC_OOO_ERROR_MASK 0X2
#define C2H_DRSR_DESC_OOO_ERROR_SHIFT 1
#define C2H_DRSR_DESC_UNALIN_ERROR_MASK 0X4
#define C2H_DRSR_DESC_UNALIN_ERROR_SHIFT 2
#define C2H_DRSR_DESC_FULL_MASK 0X8
#define C2H_DRSR_DESC_FULL_SHIFT 3
#define C2H_DRSR_DESC_EMPTY_MASK 0X10
#define C2H_DRSR_DESC_EMPTY_SHIFT 4

#define SDE_C2H_DESCRIPTOR_INFO_REG (0X1C + SDE_C2H_DESCRIPTOR_CSRS_REGS_OFFSET)
#define C2H_DIR_DESC_TYPE_MASK 0X1
#define C2H_DIR_DESC_TYPE_SHIFT 0
#define C2H_DIR_DESC_RAM_DEPTH 0XFFFF0000
#define C2H_DIR_DESC_RAM_DEPTH_SHIFT 16

#define SDE_C2H_DATA_MOVER_CSRS_REGS_OFFSET (0x200 + SDE_C2H_CSRS_REGS_OFFSET)

#define SDE_C2H_DATA_MOVER_CFG_REG (0X0 + SDE_C2H_DATA_MOVER_CSRS_REGS_OFFSET)

#define SDE_C2H_DATA_MOVER_STATUS_REG (0X4 + SDE_C2H_DATA_MOVER_CSRS_REGS_OFFSET)
#define C2H_DMSR_DM_BRESP_ERR_MASK 0X1
#define C2H_DMSR_DM_BRESP_ERR_SHIFT 0
#define C2H_DMSR_DM_DESC_LEN_ERR_MASK 0X2
#define C2H_DMSR_DM_DESC_LEN_ERR_SHIFT 1

#define SDE_C2H_WRITEBACK_CSRS_REGS_OFFSET (0x300 + SDE_C2H_CSRS_REGS_OFFSET)

#define SDE_C2H_WRITEBACK_CFG_REG (0X0 + SDE_C2H_WRITEBACK_CSRS_REGS_OFFSET)
#define C2H_WBCR_DESC_CNT_WB_EN_MASK 0X1
#define C2H_WBCR_DESC_CNT_WB_EN_SHIFT 0
#define C2H_WBCR_PKT_CNT_WB_EN_MASK 0X2
#define C2H_WBCR_PKT_CNT_WB_EN_SHIFT 1
#define C2H_WBCR_DESC_CDT_WB_EN_MASK 0X4
#define C2H_WBCR_DESC_CDT_WB_EN_SHIFT 2
#define C2H_WBCR_MD_PTR_EN_MASK 0X8
#define C2H_WBCR_MD_PTR_EN_SHIFT 3
#define C2H_WBCR_DESC_CDT_WC_EN_MASK 0X10
#define C2H_WBCR_DESC_CDT_WC_EN_SHIFT 4
#define C2H_WBCR_DESC_CNT_WC_EN_MASK 0X20
#define C2H_WBCR_DESC_CNT_WC_EN_SHIFT 5
#define C2H_WBCR_PKT_CNT_WC_EN_MASK 0X40
#define C2H_WBCR_PKT_CNT_WC_EN_SHIFT 6
#define C2H_WBCR_MD_WR_PTR_WC_EN_MASK 0X80
#define C2H_WBCR_MD_WR_PTR_WC_EN_SHIFT 7
#define C2H_WBCR_WC_CNT_MINUS1_MASK 0X3F00
#define C2H_WBCR_WC_CNT_MINUS1_SHIFT 8

#define SDE_C2H_STATUS_CNTRS_BADDR_LO_REG (0X4 + SDE_C2H_WRITEBACK_CSRS_REGS_OFFSET)

#define SDE_C2H_STATUS_CNTRS_BADDR_HI_REG (0X8 + SDE_C2H_WRITEBACK_CSRS_REGS_OFFSET)
#define C2H_SCBAHR_STATUS_CNTRS_BADDR_HI_MASK 0XFFFF
#define C2H_SCBAHR_STATUS_CNTRS_BADDR_HI_SHIFT 0

#define SDE_C2H_WRITEBACK_COAL_TMO_CNT_REG (0XC + SDE_C2H_WRITEBACK_CSRS_REGS_OFFSET)
#define C2H_WCTC_WC_TO_TICK_CNT_MASK 0XFFFFF
#define C2H_WCTC_WC_TO_TICK_CNT_SHIFT 0
#define C2H_WCTC_TICK_TO_WC_CNT_MASK 0XF00000
#define C2H_WCTC_TICK_TO_WC_CNT_SHIFT 20

#define SDE_C2H_MD_RING_BADDR_LO_REG (0X18 + SDE_C2H_WRITEBACK_CSRS_REGS_OFFSET)

#define SDE_C2H_MD_RING_BADDR_HI_REG (0X1C + SDE_C2H_WRITEBACK_CSRS_REGS_OFFSET)

#define SDE_C2H_MD_RING_SZ_REG (0X20 + SDE_C2H_WRITEBACK_CSRS_REGS_OFFSET)

#define SDE_C2H_MD_RING_RD_PTR_REG (0X24 + SDE_C2H_WRITEBACK_CSRS_REGS_OFFSET)
#define C2H_MDRRPR_MC_RD_PTR_MASK 0XFFFF
#define C2H_MDRRPR_MC_RD_PTR_SHIFT 0

#define SDE_C2H_MD_RING_WR_PTR_REG (0X28 + SDE_C2H_WRITEBACK_CSRS_REGS_OFFSET)
#define C2H_MDRRPR_MC_WR_PTR_MASK 0XFFFF
#define C2H_MDRRPR_MC_WR_PTR_SHIFT 0

#define SDE_C2H_WRITEBACK_STATUS_REG (0X2C + SDE_C2H_WRITEBACK_CSRS_REGS_OFFSET)
#define C2H_WBSR_WB_STS_BRESP_ERR_MASK 0X1
#define C2H_WBSR_WB_STS_BRESP_ERR_SHIFT 0
#define C2H_WBSR_WB_MD_BRESP_ERROR_MASK 0X2
#define C2H_WBSR_WB_MD_BRESP_ERROR_SHIFT 1

#define SDE_C2H_STATUS_DW_REG (0X30 + SDE_C2H_WRITEBACK_CSRS_REGS_OFFSET)
#define C2H_SDWR_DESC_ERROR_MASK 0X1
#define C2H_SDWR_DESC_ERROR_SHIFT 0
#define C2H_SDWR_DM_ERROR_MASK 0X2
#define C2H_SDWR_DM_ERROR_SHIFT 1
#define C2H_SDWR_WB_ERROR_MASK 0X4
#define C2H_SDWR_WB_ERROR_SHIFT 2

#define SDE_C2H_BUFFER_CSRS_REGS_OFFSET (0x400 + SDE_C2H_CSRS_REGS_OFFSET)

#define SDE_C2H_AXIS_CSRS_REGS_OFFSET (0x500 + SDE_C2H_CSRS_REGS_OFFSET)
#define SDE_C2H_PACKET_COUNT_REG (0X0 + SDE_C2H_AXIS_CSRS_REGS_OFFSET)

/* H2C CSRs */
#define SDE_H2C_CSRS_REGS_OFFSET (0xA00 + SDE_CONFIG_REG_MAP_OFFSET)

#define SDE_H2C_GLOBAL_CSRS_REGS_OFFSET (0X0 + SDE_H2C_CSRS_REGS_OFFSET)

#define SDE_H2C_DESCRIPTOR_CSRS_REGS_OFFSET (0X100 + SDE_H2C_CSRS_REGS_OFFSET)

#define SDE_H2C_DESCRIPTOR_CREDIT_CONSUMED_COUNTER_REG (0X0 + SDE_H2C_DESCRIPTOR_CSRS_REGS_OFFSET)

#define SDE_H2C_DESCRIPTOR_CREDIT_LIMIT_COUNTER_REG (0X4 + SDE_H2C_DESCRIPTOR_CSRS_REGS_OFFSET)

#define SDE_H2C_COMPLETED_DESCRIPTOR_COUNTER_REG (0X8 + SDE_H2C_DESCRIPTOR_CSRS_REGS_OFFSET)

#define SDE_H2C_DESCRIPTOR_FIFO_PTRS_REG (0XC + SDE_H2C_DESCRIPTOR_CSRS_REGS_OFFSET)
#define H2C_DFPR_FIFO_WR_PTR_MASK 0X7FFF
#define H2C_DFPR_FIFO_WR_PTR_SHIFT 0
#define H2C_DFPR_FIFO_WR_PTR_MSB_MASK 0X8000
#define H2C_DFPR_FIFO_WR_PTR_MSB_SHIFT 15
#define H2C_DFPR_FIFO_RD_PTR_MASK 0X7FFF000
#define H2C_DFPR_FIFO_RD_PTR_SHIFT 16
#define H2C_DFPR_FIFO_RD_PTR_MSB_MASK 0X8000000

#define SDE_H2C_DESCRIPTOR_RAM_ADDR_REG (0X10 + SDE_H2C_DESCRIPTOR_CSRS_REGS_OFFSET)
#define H2C_DRAR_DESC_RAM_ADDR_MASK 0XFFFF
#define H2C_DRAR_DESC_RAM_ADDR_SHIFT 0
#define H2C_DRAR_DESC_RAM_DW_IDX_MASK 0XF0000
#define H2C_DRAR_DESC_RAM_DW_IDX_SHIFT 16

#define SDE_H2C_DESCRIPTOR_RAM_DATA_REG (0X14 + SDE_H2C_DESCRIPTOR_CSRS_REGS_OFFSET)

#define SDE_H2C_DESCRIPTOR_RAM_STATUS_REG (0X18 + SDE_H2C_DESCRIPTOR_CSRS_REGS_OFFSET)
#define H2C_DRSR_DESC_OFLOW_MASK 0X1
#define H2C_DRSR_DESC_OFLOW_SHIFT 0
#define H2C_DRSR_DESC_OOO_ERROR_MASK 0X2
#define H2C_DRSR_DESC_OOO_ERROR_SHIFT 1
#define H2C_DRSR_DESC_UNALIN_ERROR_MASK 0X4
#define H2C_DRSR_DESC_UNALIN_ERROR_SHIFT 2
#define H2C_DRSR_DESC_FULL_MASK 0X8
#define H2C_DRSR_DESC_FULL_SHIFT 3
#define H2C_DRSR_DESC_EMPTY_MASK 0X10
#define H2C_DRSR_DESC_EMPTY_SHIFT 4

#define SDE_H2C_DESCRIPTOR_INFO_REG (0X1C + SDE_H2C_DESCRIPTOR_CSRS_REGS_OFFSET)
#define H2C_DIR_DESC_TYPE_MASK 0X1
#define H2C_DIR_DESC_TYPE_SHIFT 0
#define H2C_DIR_DESC_RAM_DEPTH 0XFFFF0000
#define H2C_DIR_DESC_RAM_DEPTH_SHIFT 16

#define SDE_H2C_DATA_MOVER_CSRS_REGS_OFFSET (0X200 + SDE_H2C_CSRS_REGS_OFFSET)

#define SDE_H2C_DATA_MOVER_CFG_REG (0X0 + SDE_H2C_DATA_MOVER_CSRS_REGS_OFFSET)

#define SDE_H2C_DATA_MOVER_STATUS_REG (0X4 + SDE_H2C_DATA_MOVER_CSRS_REGS_OFFSET)
#define H2C_DMSR_DM_RRESP_ERR_MASK 0X1
#define H2C_DMSR_DM_RRESP_ERR_SHIFT 0
#define H2C_DMSR_DM_DESC_LEN_ERR_MASK 0X2
#define H2C_DMSR_DM_DESC_LEN_ERR_SHIFT 1

#define SDE_H2C_WRITEBACK_CSRS_REGS_OFFSET (0X300 + SDE_H2C_CSRS_REGS_OFFSET)

#define SDE_H2C_WRITEBACK_CFG_REG (0X0 + SDE_H2C_WRITEBACK_CSRS_REGS_OFFSET)
#define H2C_WBCR_DESC_CNT_WB_EN_MASK 0X1
#define H2C_WBCR_DESC_CNT_WB_EN_SHIFT 0
#define H2C_WBCR_PKT_CNT_WB_EN_MASK 0X2
#define H2C_WBCR_PKT_CNT_WB_EN_SHIFT 1
#define H2C_WBCR_DESC_CDT_WB_EN_MASK 0X4
#define H2C_WBCR_DESC_CDT_WB_EN_SHIFT 2
#define H2C_WBCR_DESC_CDT_WC_EN_MASK 0X10
#define H2C_WBCR_DESC_CDT_WC_EN_SHIFT 4
#define H2C_WBCR_DESC_CNT_WC_EN_MASK 0X20
#define H2C_WBCR_DESC_CNT_WC_EN_SHIFT 5
#define H2C_WBCR_PKT_CNT_WC_EN_MASK 0X40
#define H2C_WBCR_PKT_CNT_WC_EN_SHIFT 6
#define H2C_WBCR_WC_CNT_MINUS1_MASK 0X3F00
#define H2C_WBCR_WC_CNT_MINUS1_SHIFT 8

#define SDE_H2C_STATUS_CNTRS_BADDR_LO_REG (0X4 + SDE_H2C_WRITEBACK_CSRS_REGS_OFFSET)

#define SDE_H2C_STATUS_CNTRS_BADDR_HI_REG (0X8 + SDE_H2C_WRITEBACK_CSRS_REGS_OFFSET)
#define H2C_SCBAHR_STATUS_CNTRS_BADDR_HI_MASK 0XFFFF
#define H2C_SCBAHR_STATUS_CNTRS_BADDR_HI_SHIFT 0

#define SDE_H2C_WRITEBACK_COAL_TMO_CNT_REG (0XC + SDE_H2C_WRITEBACK_CSRS_REGS_OFFSET)
#define H2C_WCTC_WC_TO_TICK_CNT_MASK 0XFFFFF
#define H2C_WCTC_WC_TO_TICK_CNT_SHIFT 0
#define H2C_WCTC_WC_TO_CNT_MASK 0XF00000
#define H2C_WCTC_WC_TO_CNT_SHIFT 20

#define SDE_H2C_WRITEBACK_STATUS_REG (0X10 + SDE_H2C_WRITEBACK_CSRS_REGS_OFFSET)
#define H2C_WBSR_WB_STS_RRESP_ERR_MASK 0X1
#define H2C_WBSR_WB_STS_RRESP_ERR_SHIFT 0
#define H2C_WBSR_WB_MD_BRESP_ERROR_MASK 0X2
#define H2C_WBSR_WB_MD_BRESP_ERROR_SHIFT 1

#define SDE_H2C_STATUS_DW_REG (0X14 + SDE_H2C_WRITEBACK_CSRS_REGS_OFFSET)
#define H2C_SDWR_DESC_ERROR_MASK 0X1
#define H2C_SDWR_DESC_ERROR_SHIFT 0
#define H2C_SDWR_DM_ERROR_MASK 0X2
#define H2C_SDWR_DM_ERROR_SHIFT 1
#define H2C_SDWR_WB_ERROR_MASK 0X4
#define H2C_SDWR_WB_ERROR_SHIFT 2

#define SDE_H2C_BUFFER_CSRS_REGS_OFFSET (0X400 + SDE_H2C_CSRS_REGS_OFFSET)

#define SDE_H2C_AXIS_CSRS_REGS_OFFSET (0X500 + SDE_H2C_CSRS_REGS_OFFSET)

#define SDE_H2C_PACKET_COUNT_REG (0X0 + SDE_H2C_AXIS_CSRS_REGS_OFFSET)
